class FatigueQuiz {
  var images = ['blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank',
  'blank', 'blank', 'blank', 'fa14', 'blank', 'blank', 'blank', 'fa18', 'blank', 'blank',
  'blank', 'fa22', 'blank', 'blank', ];

  var questions = [
    'Hun ngeina/hoih nuaihah mawtaw khat peuh nungah bangzaha hatin na tai zongin',
    'Khuasia nuaiah mawtaw na hawl leh na mawtaw',
    'Zanin nang lam hong zuan mawtaw ii mei taang in hong leng/salh leh',
    'Mawtaw hawl laitak na ihmut a suak leh',
    'Khuasia nuaiah/Guah zu meiikai nuaiah khua na muh theih mel loh ciangin',
    'Na mawtaw hawl laitakin guah hong zuk leh',
    'Zingsang daitui in a nelsak lampi banga lampi kawt/lampi nalah na hawl ciangin na mawtaw',
    'Lampi kawt tungah banghangin brake nakpi taka sik lo ding nahi hiam?',
    'Zan ciangin',
    'Sun ahi a, zan ahizongin meii(cloud) a tam mahmah a, na mawtaw-ah meei kapna meivak a om kei leh',
    'Khual gamlapi mawtaw na hawl ciangin hih a nuaiate lakah koi kisam/phamawh pen hiam?',
    'Zanin nang lam hong zuan mawtaw tawh na kituah ding ciang',
    'A nuai-a koi lungsim puakzia in a lungmuanhuai mawtaw hawl hong hisak ding upmawhhuai pen hiam?',
    'Mawtaw khawlna pan na taikhiat ding ciangin na hih ding nunung pen bang hiam',
    'Mawtaw khawlna panin na paikhiat ciangin mawtaw dang, mihing leh ganhing sukkhak loh dan hoih pen bang hiam?',
    'Mi tampi in mawtaw a hawl cil kum masa sungin tuahsiatna tuak uh hi. Tuahsiatna tuak hek lo-a mawtaw hawl kisin dan hoih pen bang hi ding hiam?',
    'Mawtaw hawl ciangin lampi bangci hiam ci-a sit/ettel (scan) ding thupi mahmah hi. "Lampi sit/ettel"(scan) i cih in bangteng huam hiam?',
    'Mawtaw-hawl thak na hi a, zana hawl na kipatcilna ahih leh',
    'A gamla sima om na lawmte kiang hawh dingin na dingkhia hi. Bangtan hiam khit ciangin tawl na kisa hi. Bang cih ding na hiam?'
    'Meltheih khangham  khat, paina ding sehsa(appointment) nei na pua hi. Na paina dinguh na zekai uh a, hat tai dingin hong nawh ciang',
    'Na lawmte pawlkhat tawh Sydney panin Gold Coast dong mawtaw hawl dingin na geel hi. Cikham/ihmutsuak a phatuam sak ding leh na khualzinna uh ah lungmuanhuai theih pen nadingin',
    'Na mai-a mawtaw tawh na kikalna uh awng sak in. Hun hoihna ah na kihalna uh pen',
    'Zan hun hi-in, cinema etna panin inn lam zuanin na hawl hi. Lampi ah mawtaw dangte tawh kigualin na tai hi. Na mawtaw leh na mai-a mawtaw kihalna bangzah hi ding hiam?',
    'A lauhuai, awlmawh neilo, mi khualna neilo mawtaw hawl khat na tuak kha hi',
  ];

  var choice = [
    ['Na mai-a mawtaw tawh second khat beekin kihal in', 'Na mai-a mawtaw tawh a kinai thei bang penin tai in', 'Na mai-a mawtaw tawh second thum beekin kihalin tai in'],
    ['control baih zaw ding ahihmanin na hat tai thei hi', 'Khuaphat huna na kihalsak ngei zah mah a kihal sakding', 'Khawlsak pah hamsa ahih manin dampai sak in'],
    ['Na mit ngeina a bat dong tawmvei mitsi in', 'Lampi laizang en in', 'Na mit ngeina a bat dongin dampai sakin'],
    ['Radio ngeih taka hon hoih pen hi', 'Khawl ding, tawlnga ding, a kisap leh a hawl kilaih ding hoih pen hi', 'Huih vot(air conditioning) hong ding ahih kei leh, padenpoh (windows) hawng ding hoih pen hi'],
    ['Mawtaw mei (headlight) taang sakin dampai sak inla, na mai-a mawtaw tawh a zahnih bangin kihal in', 'Mi dangte na hilhna in na mei(headlight) tang sakin', 'Na mei(headlight) a taang pen (high beam)in koih in'],
    ['Khua na hoih muh theih zawk nadingin na meitaang a taang penpen(high beam)in koihin', 'Guahtui leh sathau ten lampi nal sak theih ahih manin dam takin na brake sik inla, dampai sak in', 'Hazard mei taang sak inla, guahzu na pelh pah theih nadingin hat takin tai in'],
    ['Na mawtaw na khawl nadingin hun leh mun sau kisam hi', 'A hawl baihzaw hi', 'A hawl hamsa zaw hi'],
    ['Khe paina a pai mite na kawt sak kha ding hi', 'Na mawtaw peite taang/awk kha leh na brake in nasem lo ding hi', 'Na mawtaw peite kitaalin na mawtaw na ukzo kei kha ding hi'],
    ['Mawtaw dang na makhelh ding ciang na hazard mei taang sakin', 'Na mai-a mawtaw tawh na kihal zaw sem ding hi', 'Na mai-a mawtaw ten hong muh cian theih nadingun amau tawh a kinai-in hawl in'],
    ['Mawtaw dangte nai-ah zui-in', 'Meitang mahmah(high beam) in vakin', 'Na mawtaw a kimuh theih nadingin na mawtaw mai meivak(low beam) leh hazard warning mei taang sakin'],
    ['Na horn a hoih leh ahoih cian in', 'Na kipat ma-in limtak tawlnga hithiat in', 'Na mawtaw hawl ma-in ann lim ann pha ne in'],
    ['Lampi veilam enin veilamah neh in la, a mawtaw mei taang en kei in', 'Na mawtaw a kimuh baih theih nadingin na mawtaw meivakte a taang penpen(highbeam) ah koih in', 'A mawtaw-mei vaak en kawmin limtakin encik in'],
    ['Tuahsiat leh tuahsiat loh pen kaam(luck) thu hi', 'Tuahsiatna pelh ding pen midangte thuthu hi/midangte tungah kinga hi', 'Mawtaw ka hawl ciangin kei leh lampi zang mite bitna pen ka tavuan lianpi hi'],
    ['Na tutna lempha in', 'Na liangko tungah nunghei in sitin', 'Tutna kigakna thuahin/Tutna kigakna tawh kigak in'],
    ['Na hawlkhiat ma-in hawlkhia ding nahih lam theihsakna in horn pia in', 'Na mawtaw na zuat kawmin na kiim leh paam hoih takin enin la, na kin theih bangpenin taikhia hi', 'Mawtawkhawlna panin na hawlkhiat ma-in na mawtaw maan sitin na lu nunghei in sittel masa in'],
    ['Mawtaw hawl na siam mahmah khit ciangin bekin mipi tamna-ah hawl in, tuama siah mi tawmna bekah hawl in', 'License na neih phetin paisuk paitohna om thei bangbangah hawl pahin', 'Party te ah lawmte tawh na pai ciangin a tam hawl pha deuh in'],
    ['Mawtaw hawl cianga a nunglam etna maan leh a gei-a maan omte a kizom taka et', 'Mawtaw hawl ciang, a kizomtaka mai lam et, vei leh tak et leh maan omte limtaka zat', 'Mawtaw hawl ciang mailam saupi et'],
    ['Na ngaihsutna(concentration) na piak theih nadingin gamlapi tak hawlin', 'A diakdiakin na theih ngeiloh lampite ah hawlin', 'A diakdiakin na theihsa lampite ah hawl in'],
    ['Na tawldam dong lam-nawlah khawl ding, tawlnga ding', 'Na mawtaw sungah huih siang tampi hong lut theih nadingin na mawtaw padenpoh maante hong ding', 'Na ihmut a suak loh nadingin sai khatpeuhah khawlin caffeine om dawn theih khatpeuh dawn ding'],
    ['Meileng station ah kha in', 'Kum tampi mawtaw a hawlte kiang lamlahna ngen kawmin na hat tai theihna mun peuhah hat sak in', 'A lauhuai lo ciang speed tawh hatsak in tai inla, tua sanga hatzaw in tai kei ning ci-in'],
    ['Sun sung bekin hawl ding, tamveipi khawl ding, ahih theih leh mawtaw hawl kilaih ding', 'Na tun baih theih nadingun nuam nasak sungin a gamla theithei tun sawmin', 'Zanin mawtaw tai tam lo ahih manin zan sungin tai zaw ding, tua hileh tatkhialh theihna zong tawm zaw deuh ding'],
    ['1 second', '3 second', '2 second'],
    ['Zanin mawtaw kihalna theih khialh baih ahih manin 4 second bangin kihal ding', 'Sun hun sunga second 3 na kihal bangun zanin zong kihal ding', 'Na mai-a tawh 2 second bangin kihal ding, tua hileh a khawl dinguh kician takin na mu thei ding hi'],
    ['Patau lo-in na mawtaw na control in na om tawntung ding hi', 'Mawtaw hawlpa mawtaw hawl dan hilh dingin delh in', 'Horn pia ahih kei leh mawtaw mei taangsakna tawh mawtaw hawlpa in na veina/phawkna kilang sakin'],
  ];

  var correctAnswers = 
  [
   'Na mai-a mawtaw tawh second thum beekin kihalin tai in',
   'Khawlsak pah hamsa ahih manin dampai sak in',
   'Na mit ngeina a bat dongin dampai sakin',
   'Khawl ding, tawlnga ding, a kisap leh a hawl kilaih ding hoih pen hi',
   'Mawtaw mei (headlight) taang sakin dampai sak inla, na mai-a mawtaw tawh a zahnih bangin kihal in',
   'Guahtui leh sathau ten lampi nal sak theih ahih manin dam takin na brake sik inla, dampai sak in',
   'Na mawtaw na khawl nadingin hun leh mun sau kisam hi',
   'Na mawtaw peite kitaalin na mawtaw na ukzo kei kha ding hi',
   'Na mai-a mawtaw tawh na kihal zaw sem ding hi',
   'Na mawtaw a kimuh theih nadingin na mawtaw mai meivak(low beam) leh hazard warning mei taang sakin',
   'Na kipat ma-in limtak tawlnga hithiat in',
   'Lampi veilam enin veilamah neh in la, a mawtaw mei taang en kei in',
   'Mawtaw ka hawl ciangin kei leh lampi zang mite bitna pen ka tavuan lianpi hi',
   'Na liangko tungah nunghei in sitin',
   'Mawtawkhawlna panin na hawlkhiat ma-in na mawtaw maan sitin na lu nunghei in sittel masa in',
   'Mawtaw hawl na siam mahmah khit ciangin bekin mipi tamna-ah hawl in, tuama siah mi tawmna bekah hawl in',
   'Mawtaw hawl ciang, a kizomtaka mai lam et, vei leh tak et leh maan omte limtaka zat',
   'A diakdiakin na theihsa lampite ah hawl in',
   'Na tawldam dong lam-nawlah khawl ding, tawlnga ding',
   'A lauhuai lo ciang speed tawh hatsak in tai inla, tua sanga hatzaw in tai kei ning ci-in',
   'Sun sung bekin hawl ding, tamveipi khawl ding, ahih theih leh mawtaw hawl kilaih ding',
   '3 second',
   'Zanin mawtaw kihalna theih khialh baih ahih manin 4 second bangin kihal ding',
    'Patau lo-in na mawtaw na control in na om tawntung ding hi',
  ];

}