class GeneralKnowledgeQuiz {

  var images = ['blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'gk9', 'gk10',
  'gk11', 'blank', 'blank', 'blank', 'blank', 'gk16', 'blank', 'blank', 'gk19', 'blank',
  'blank', 'blank', 'blank', 'gk24', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 
  'gk31', 'gk31', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank', 'blank',
  'blank', 'blank', 'blank', 'blank', 'blank', 'gk46', 'gk47', 'blank', 'blank', 'blank',
  'gk51', 'gk52', 'gk53', 'gk54', 'gk55', 'gk56', 'gk57', 'gk58', 'gk59', 'blank',
  'gk61', 'gk62', 'gk63', 'gk64', 'blank', 'gk66', 'gk67', 'gk68', 'gk69', 'gk70',
  'gk71', 'blank', 'blank', 'gk74', 'gk75', 'blank', 'blank','blank', 'blank', 'blank',
  'gk81', 'blank', 'blank', 'blank', 'blank'];

  var questions = [
    'Knowledge test ah na etteh/khemlam hong kithei leh bang hong kicih ding hiam?',
    'Mawtaw hawl na on(pass) theih nadingin hong sit officer te golhguk pia lecin bang hong kicih ding hiam?',
    'Mawtaw hawl na on(pass) theih nadingin hong sit officer te in golhguk hong ngenin pia le cin, bang hong kicih ding hiam?',
    'P1 or P2 mawtaw hawlte in thukhun bangin (legally) midangte mawtaw hawl a sinsak thei mah uh hiam?',
    'P1 license neite in P2 license a ngah theih nadingun P1 license a tawi uh bangtan sawt ding', 
    'Lampi nawl/kil tungah na mawtaw pei khat maw nih maw hong om leh bangcih ding na hiam?',
    'Lampi tungah lamzing (lane) ciaptehna (mark) om kei ta leh, koici hawl ding',
    'Freeway ah na mawtaw a siat ciang',
    'Veilamah kihei na sawm ciang theihsakna(signal) na piak akul hiam?',
    'Leii(bridge) tung hiam a gei hiam khatah hih lim/ciaptehna a om leh bang cih ding na hiam?',
    'Na kilehhei (reversing) ciang',
    'Lamgei ah kigualin(parallel) mawtaw na park ciang, mawtaw khat le khat bangci kihal ding',
    'Lamgei ah kigualin(parallel) mawtaw park na munah, mawtaw khawlsa khat belin park thuah(double park) ding hong kiphal hiam?',
    'Mawtaw lampi ah na mawtaw kongkhak na hon ciangin bang mawhpuakna nei na hiam?',
    'Lampi kikal mun awng(traffic island) ah mawtaw park ding hong kiphal mah hiam?',
    'Hih thaltang kawkna lamah mawtaw koih hong kiphal hiam?',
    'Khuanim ni, nitum kuan leh nisuah kuan hunah mawtaw na hawl leh bang nahih ding kisam hiam?',
    'Zanin mawtaw meitaang lela (high beam) sa-in na hawl hi. Bang hun ciangin mawtaw meitaang (low beam)ah khiam ding na hiam?',
    'Speed limit 60 km/h taina huamah na hawla, lamzing khat bek omna, Na mai-ah bus (hih ciaptehna) a omna munah Khawlmun pan apai khia ding bus in signal a lah lam na mu hi. Bang cih ding na hiam?',
    'Na mawtaw nambat kician taka muhtheih loh dingin na liah/dal sakpen thukhun palsat na hi hiam?',
    'Freeway-ah na tai ma-in hih a nuaiate lakah bang na hih kul hiam?',
    'Freeway panin na pusuah(exit) nadingah pusuak kha lo-in paisuak kha lecin bang cih ding na hiam?',
    'Freeway na nusiat ciangin, hih a nuai-a te lak panin koipen cian(check) pelmawh ding na hiam?',
    'Bung hun ciangin hih lim/ciaptehna tawh a kiciamteh lamzing(lane) ah mimal mawtaw tai thei ding hiam?',
    'Trailer(van kaihna) khat sanga tamzaw nunglamah kai hawl ding hong kiphal mah hiam?',
    'Inn mawtaw (caravan) na kaih laitak mawtaw dangte in hong makhelh theih nadingin bang cih ding na hiam?',
    'Inn mawtaw(caravan) sungah mi tuang kawm sa-in kaih ding hong kiphal mah hiam?',
    'Mawtaw sungah van dimpi ahih kei leh hattaka gamlapi mawtaw na hawl ding ciangin',
    'Nang lam hong zuan hong lehpai mawtaw in lampi laizang git khengin nang lam hong manawh hong hen la, na mawtaw khawlsak pak ding hi thei kei leh bang cih ding,',
    'Accident na tuak kha a, na mawtaw kaihkhiat kulin hong huh dingin palikte om kei ta leh',
    'Na mawtaw tuahsiatna-ah (mawtaw sia ngaihsun lo in), na kitaihpih mawtaw hawl dangte tawh bang kipia masa ding na hih uh hiam?',
    'Mawtaw tuahsiatna (accident)ah na kihel a, mi khat liam leh, na khawl khit teh bang hih pelmawh ding na hiam?',
    'Meileng lamkaanna-ah Khawl ding cih ciaptehna (stop sign) ahih kei leh mei phia (flashing light) te a tawntungin zuih ding hi, a hang pen',
    'Bang hun ciangin meileng lam tawh kikim lamkanna(level crossing) te-ah lamkaan lo ding na hi hiam',
    'Taklam theihsakna(indicator) mei banghun ciangin zang ding na hiam?',
    'Freeway lutna panin Freeway sung na lut ciangin',
    'Lampi kibawl/kipuahpha hi cih lahna lim/ciaptehna na muh leh',
    'Lamnawl tawh kineh in a tawngtawnga lam kigit anai pak (broken yellow line) na mu hi. Bang deihna ahi hiam?',
    'Lampi tungah sakol tungtuang na muh leh bang cih ding na hiam?',
    'Mi sawm(10) atuan theihna mawtaw(van) na lawmte khatin hong zang sak hi. Hih mawtaw hawl nadingin bang dan license nam kisam na hiam?',
    'Na mawtaw hawl hong nawngkai sak thei ding damlohna na tuah ciangin bang hih kisam na hiam?',
    'Na lawmte khatin a mawtaw hong zangsak/kawm hi. Tua mawtaw lim gin mahmah a, a khu nasia mahmah hi. Tua mawtaw pen genbang hi ci-in letmat hong kipia khin napi-in hawl thei lai veve hi teh hong ci hi. Bang cih ding na hiam?',
    'Na mawtaw ii register(tet-tan) tuni-in a hun bei hi. Na mawtaw tettan khan dingin hong kisit(inspection) in ong(pass) lo hi. Bang cih ding na hiam?',
    'Mawtaw na lei a, tyre aval(spare tyre) pen maat(smooth) mahmah khin a, a khauzang te zong kimu thei hi. Na mawtaw pei kitam na khat om zen zen leh tua tyre val(spare tyre) hoih nawnlo pen zat hong kiphal mah hiam?',
    'Na lawmte mawtaw na kawm hi. A hawlte tutna leh a hawlna ki gamla mahmah hi. Bang cih ding?',
    'Ciangtanna nei lo license (unrestricted license) na nei a, 100 km/h hatin khuapi pua lamah na tai/hawl a, hih lim/ciapteh na tuak hi. Bang ci ding na hiam?',
    'Taklam pial theihna lamzing(lane) nih panin taklamah na pial nuam hi. Theihsakna mei(indicator) bangci piak ding na hiam?',
    'Red Light Camera (Lam kan hun lohpi-a a kaan teitei mawtaw maan zaihna) omna lamka bomah na tai hi. Traffic mei a naipak(yellow) tangta a, khawl dingin lamkabom tawh na kineh lua ta a, lem nawnlo ahih manin na tai suak hi. Traffic mei a san lian leh lamkabom agal khat lam na tung khin hi. Daan(penalty) theihsakna lai hong kipia ding hiam?',
    'Freewayah mawtaw na hawl laitakin innah mangngilh khat na neih lam na phawk hi. Na kileh nuam a, hih lampi-ah U-turn zangin na kihei thei hiam?',
    'Mawtaw sungah naupang kum 6 mi khat tawh na om hi. Mawtaw na khawlsak(parked) khin a, Zatui sai(Chemist) ah zatui thoh dingin na om ta hi',
    'Lamto(sloping uphill) ah na mawtaw na koih(park) nuam hi',
    'Koi mawtaw pen a maanin ki park hiam?',
    'Hih ciaptehna/lim na kheng lian hi. Hih lampi ah mawtaw na khawlsak thei hiam?',
    'Lam laizang a Kikhenna giit nih (double dividing lines) omna ah',
    'Mawtaw khawlna munah mawtaw khawl zia ding hilhna leh ciaptehna a om kei leh, hih mawtaw khawl dante lakah koi pen maan hiam?',
    'Bang hun ciangin mawtaw a sawi-a koih(angle park) ding?',
    'Hi leii(bridge) tungah mawtaw nih bek ta/tai thei hi. Na tun dektak ciangin',
    'Hih anuai-a maante lakah koi maan pen hiam?',
    'Hih lamka/lampi kituahna munah kidawm mahmah in, a hangin',
    'Lampi mawtaw tam mahmahna ah na tai a, setbing tuang khat hangin na dam tai hi. Na nunga mawtaw hawlte in setbing awn in na hatsak nadingin horn hong pia hi. Bang cih ding na hiam?',
    'Na nunglam panin zato mawtaw ging in hong pha dektak ciangin',
    'Hih lampi ah mawtaw na hawl hi. Zato mawtaw ging na za a, na mawtaw maan pan na mu thei hi',
    'Lampi kituahna pan taklamah na kihei nuam hi. Nanga dingin traffic mei eng hi. Patau mawtaw ging na za a, meiphelh mawtawpi in hong makhelh pah ding cih na mu hi',
    'Lam kibawlna mun na tuah ciang',
    'A tangpi thuin patau mawtaw ging na zak ciangin',
    'Mawtaw A tawh traffic mei eng na zuan hi. Patau mawtaw ging kawmin hong tai a, traffic mei san khinta hi',
    'Bus nungah hih mei taang na muh ciang bangcih ding na hiam?',
    'Zanin mawtaw na hawl hi. Na kiimah mawtaw dang omlo hi. Bang hun ciangin na mawtaw mei atang lela(high beam) ah koih thei na hiam?',
    'Zan sungin na mawtaw tawmvei sung na khawlsak(park) nuam hi',
    'Lamkiu suang nen omna ah mawtaw na hawl hi',
    'Khen nih a kikhen lampi(tow-lane-freeway) ah na tai ciangin koilamah tawn/tai ding na hiam?',
    'Freeway lampi zing(lane) thum a om ciangin',
    'Na mai-a bus ii meitang a phia na muh ciangin bang hih ding na hiam?',
    'Lampi ah mawtaw na hawl a, tom cik sung nakhawl nuam hi. Lam geia mawtaw khawl omsa zawmah nakhawl ding(double park) a kingah hiam?',
    'Hih lim enin bus khawlmun lutna lam pan ahih kei leh meileeng lamkanna panin bangtana gamla ah din or khawl ding hong kiphal hiam?',
    'Mawtaw na hawl kawmin khut tawh let mobile phone zat hong kiphal hiam?', 
    'Mawtaw na hawl simin na mawtaw hawl theihna license na puak den ding akisam hiam?',
    'Setbing hawlte leh mawtaw saikel hawlte in mawtaw dang hawlte mah bangin lampi zang thei uh hi. Ahizongin, amaute aa dingin a lauhuai zawkna pen',
    'Lauhuai lo takin mawtaw hawl theihna dingin i kiim leh paama thupiangte lakpan kikep theih nadingin lungsim piak(concentrate) kul hi. Tua dingin',
    'Lampi kibawlna "Stop" sign/ciaptehna kikoihna lam zuanin na hawl ciangin',
    'Veilam lamzing(lane) lam kibawlna huamah mawtaw na hawl laitakin hih lim/ciaptehna na mu hi',
    'Mawtaw tung a koi-lai/sanah L or P kigelhna suang ding hiam?',
    'L or P plates a kisuan ciangin a laimal bangtan kician takin kidawk sak ding hiam?',
    'Mawtaw hawlte leh mawtaw saikel hawlte bangin setbing hawlte inzong dikna(right) leh mawhpuakna kibangin a nei uh hiam?',
    'Na mawtaw pan na pusuak ma-in',
  ];

  var choice = [
    ['Bangmah, gawtna om lo', 'Test dang na neih kik ding kiphal nawn peuhmah lo', 'Kal 6 sung test dang na neih ding hong kiphal lo ding'],
    ['Hong kithuhilh ding a, sum liau leh thongkiat dongin gawtna hong kipia thei hi', 'Bangmah, gawtna om lo ding', 'Hong sit officer bek thu kibawl ding hi'],
    ['A kihel kha khempeuh tungah thu kibawl dinga, sum liau leh thongkiat dongin hong kigawt ding hi', 'Hong sit officer bek thu kibawl ding hi', 'Gawtna om lo ahihmanin bangmah hong kicih lo ding'],
    ['He, P2 license a neih zawh kha 6 a val nak leh', 'Hilh/sinsak thei lo', 'He, L leh P1 or P2 cih a kisuan nak leh'],
    ['Kha 18', 'Kha 12', 'Kha 24'],
    ['Damdam in paisak inla lampi tungah pai kik ding', 'Hatsak semsemin lampi tungah kah kik ding', 'Brake deihtaka sik kawmin dampai sak semsem ding'],
    ['Lampi laizang tawn ding', 'Na tot na lam khat peuhpeuh ah hawl lel ding', 'Lampi veilam naih lamah hawl ding'],
    ['Veilama emergency lamzing(lane)ah kikhin in', 'Hong kimuh theih nadingin taklam lamzingah kikhin in', 'A siatna munah mawtaw kai(tow truck) mawtawpi ngak in'],
    ['Lampi tungah thaltang lim aki suah nak leh kul kei', 'Lampi tungah Veilam bekah kihei thei cih ciaptehna (mark) a om leh kul kei', 'He, kihei ding theihsakna(signal) mei mawtaw-ah a kithuah leh'],
    ['Taina lam ih kibatpih mawtaw dangte makhelh sawm ken', 'Leii na kaan ma-in khe tawh leii a kaan khatpeuh a omkhak leh lam awnin khawl in', 'Dampai sak inla, hong leh pai (nang lama hong tai) mawtawte lam awn dingin kiging in'],
    ['Mawtaw hawl dangte theihsakna in horn pia in', 'Manlang taka a kilehhei vat theih nadingin na tutna gakna phel in', 'Kidawm in, akisam zah sangin a gamla zaw leh hun akisapna munte ah kilehhei peuhmah ken'],
    ['A nung leh mai-ah 1 metre beek hal/hawi ding', 'A nung leh mai-ah 3 metres beek hal/hawi ding', 'A mai lam bekah 2 metres beek hal/hawi ding'],
    ['kingah vet lo', 'He, lampi a khak kei naak leh', 'He, van puak i hih nak leh'], 
    ['Neilo, tuabang dan zuih ding om kei', 'Neilo, mawtaw kongkhak a nawngkai sak mawtawte khawl lel ding uh hi', 'He, lampi paite aa dingin alauhaui thei leh anawngkai sak thei ahih leh mawtaw kongkhak hong sedah in'],
    ['He, sun hun sungin', 'Ai, kiphal vet lo', 'He, ahih hangin minute 30 sanga sawt lo ding'],
    ['He, passenger nih leh thum na puak leh', 'Taxi khawl dang a om kei leh kingah', 'Kingah ngiat lo'],
    ['Hazard mei taang sak ding', 'Mawtaw meitaang in na mit hong mang sak lohna dingin mitmaan vom (sunglasses) bulh in', 'Mawtaw mei aniam (low beam) in tangsak ding'],
    ['Nang lam hong zuan mawtawte metre 200 banga na kinaih uh ciang bek', 'Na mai a mawtaw ahih kei leh Nang lam hong zuan mawtaw tawh metres 200 banga na kinaih uh ciang', 'Niam sak se lo ding, a tawntungin na mawtaw meitaang lela (high beam) sa-in na hawl den thei hi'],
    ['Dampai sak inla, bus masak sak ding cih om ahih manin bus lam awn in', 'Na tai ngeina ahatzah mah in tai suak lel in, bus masak ding cih om tuan lo hi', 'Bus hong taikhiat loh nadingin na horn pia in'],
    ['He, ahizongin, mawtaw kai mawtawpite leh mawtaw nunga setbing puakna aneite in a nambat suan liah thei uh hi', 'He, banghun banghun in', 'Hilo, na ut leh na nambat suanna na liah thei hi.'],
    ['Lam hong hilh ding GPS (stree directory) hong in, lam mang kha le cin', 'Na mawtaw ah datsi, sathau, tui a kicing hiam cih leh na tyre a puak mah hiam cih cian masa in', 'Mawtaw na hawl ma-in hong tawldam sak thei na khat peuh ne masa in'],
    ['Khawl pah inla, kilehhei kik pahin', 'Khawl pah inla, na puaksuakna ding ciang dong kihei se loin nung kik in', 'Pusuak theihna ding(exit) dang na tun masiah tai suak lelin'],
    ['Mawtaw mai maan nul ding', 'Datsi tehna', 'Na (speed)tai hatna zah'],
    ['Na kihei ding metre 100 sungah', 'Mawtaw dang makhelh nading bekin', 'Passenger nih ciang beek na puak ciangin'],
    ['He, van kaihna(trailer) akigawmin a sauna metres 15 a khen kei naak leh', 'Kiphal ngiat lo', 'Kum nih sung license na neih khit naak leh kingah'],
    ['Khawl pahin la, nang sanga a hattai zaw mawtawte kimakhelh sakin', 'Taihat theih zah ding a kicih sang 25/km aa niamin tai in', 'Mawtaw liante leh inn mawtaw(caravan) a kai mawtaw dangte tawh metres 60 bang peuhmahin kihal in'],
    ['Kiphal ngiat lo/Kingah ngiat lo', 'Inn mawtaw(caravan) sunga tuangte kum 12 tung siah ahih naak uh leh kingah hi', '60 km/h sang na hatsak kei naak leh kingah'],
    ['Na paina ding na theihtheih nadingin GPS na neih leh neih loh cian masa in', 'Na mawtaw pei(tyre) huih a dim hiam cih cian masa in', 'Coffee hai khat leh an tampi ne in'],
    ['Na tai nading ahi lo lamah tai-in', 'A kihei khiat ding lamenin dampai sakin', 'Brake sik inla, na veilamah mun awng en inla, na horn pia kawm sa-in na mei phia sak in'],
    ['Palikte kiangah na tuahsiatna uh na puak kul se lo hi', 'Na tuahsiatna (accident)-na mun uh tawh kinai pen Palik zumah nai 24 sungin na tuahsiatna thu puak pelmawh in', 'A liam a om aleh bek palikte kiangah na tuahsiatna thu puakpan in'],
    ['Na license ensak inla, amau ii license(or details) zong maan zaih inla kemin, mawtaw nei te min leh tenna(address)te zong kithei sak un', 'Palik khat peuhin hong dot leh na min leh na teenna cian takin hilh in', 'Insurance company te tawh na kizop masiah nangtawh kisai min or lincese(details) te piak kul lo hi'],
    ['Accident-na hangin dollar 500 sanga tam zaw van siatsakna a neih leh bek palik sam in', 'Kisam bangin huh pah inla cina mawtaw (ambulance) sap nading ma la pahin. Tua khit teh palikte ko in', 'Ni sagih sungin accident vai palikte kiang puak in'],
    ['Mawtaw brake kisia zel hi', 'Khe tawh lampai te\'n na kaan thei uh hi', 'Meilengte hatin gikuh ahih manin khawl pahpah thei lo uh hi'],
    ['Meileeng khawlna(station) a nai leh', 'Inn mawtaw(caravan) kai nahih cianga', 'Lampi gal khat lam a awn kei(block) a leh'],
    ['Na khawl ding ciangin', 'Na dampai sak sawm ciangin', 'Taklamah pial na sawm hun peuhpeuh ciangin'],
    ['Horn pia in la, theihsakna(indicator) mei taangsak in lutin', 'Mawtaw kihal mahmah hun en in la, mawtawte hatna tawh kituakin tai in', 'Freeway lutna ah khawlin na nunglamah mawtaw a om hiam cih en in'],
    ['Dampai sak inla, lampi ukte lamlahna zui in', 'Na hat ngei-in hat sakin', 'Khawl pah inla, lamlahna ngak in'],
    ['Hih huam sungah na ut hunhunin nai khat sung mawtaw na khawl sak thei hi', 'Mawtaw khawl ding akikham hunin hih huamah na khawl het kei ding hi', 'Setbing tuangte in hih git zui ding uh hi'],
    ['Sakol tungtuangpa/nu hilhna in na horn ging sak in', 'Dampai sak inla, mun zapi awn in', 'Sakol na makhelh nadingin hat sak in'],
    ['Mawtaw neu(Car) license', 'Bus neu license', 'Mawtawpi license'],
    ['Na zato savuan (doctor)te hilh in la, aman RTA te na zasak sawn ding hi', 'Na omna pan a nai pen palik zumah na license ap in', 'Na dinmun na kitheih phetin RTA zasak pah in'],
    ['Mawtaw na kawm ma-in genbang hi cihna lai panin hawl kiphal/kingah mah ahi hiam cih kancian masa in', 'Mawtaw kawm inla, ahizongin mawtaw dangte aa dinga lauhauina a om lohna lampi bekah hawl in', 'Mawtaw kawm in la, ahizongin taihat zah ciangtan sanga 10 km/h a niam zaw in hawl in'],
    ['RTA te\'n ki register lo dingin a ngaihsut khit uh teh na mawtaw puahphat nadingin ni sagih na nei hi', 'Register abei ni a Zingcianga kipan na mawtaw a kipuahphat a, inspection (sittelna) onga, a ki register masiah hawl khia nawn kei in', 'RTA ah va pai-in na register tettan khan nget kawmin na mawtaw puahpha ding na hih lam thei sak in'],
    ['He, ahih zongin nai 24 sungin mawtaw pei a thep/vang pen bawl sak ding', 'A tyre val(spare) ahih hangin tyre maatsa(hoihlo) zat pen kiphal lo/daan kalh ahi hi', 'Tyre hoihtakin huih a kimut a, a pangteng a hoih lai naak leh kizang thei hi'],
    ['Na nungdap ding na lawm kiangah ngen in', 'A nuamlo bangin zang lel in, na lawmte tutna lepsa puahsak se dah in', 'Nang aa dingin a hoih bekin a tutna khin in'],
    ['Gan aki khawite lampi hong lut lohna dinga gawl/dai tawh ki-um ahih naak leh 100 km/h a hatin na tai suak thei hi', 'Gan kikhawite phu kha lo-a na khawl pah theih nadingin dampai sak in', 'Lo-a gan kikhawite omna 5 km sunga 60 km/hr a tai ding cih ciaptehna na tuah masiah'],
    ['Taklam kihei ding ha hih manin na taklam theihsakna mei(right indicator) pia in', 'Theihsakna mei(indicator) na piak ding nang thu hi. Mataw dangte huh thei ding cih na ngaihsut leh taklam theihsakna mei(indicator) pia in', 'Mawtaw hawl dangte na buaisak khak loh nadingin theihsakna mei(indicator) zang se kei in'],
    ['Daan/Ngawtna ngah lo ding. Ahangin, traffic mei a san khit nunga a tai suaksuak teitei te bek maan kizaih hi', 'He, ahizongin mawtawhawlnu/pa palikten thuhilhin thukhen zumah thu kitun ding hi', 'Traffic mei a san hong kilaih laitakin lamkabomah om lai nahih manin daan ngah thei ding'],
    ['Bang hun bang hunin kileh kik thei', 'Kileh kik ding kingah ngiat lo', 'Lampi kizopna(gravel joining road) na zat naak leh kileh kik thei'],
    ['Na gei-a tu khangham khat peuh kiangah na naupang/ta hong et sak dingin na vaikhak ding hi', 'Naupang mawtaw sungah nusia in', 'Naupang tonpih in'],
    ['Lampi a zangna(lamtoh lohna) mun bekah mawtaw park in', 'Handbrake kaamin, a gear(transimission) "P" ah koih in', 'Lamnawl dalna(kerb) te leh na mawtaw pei kineh sak ken'],
    ['Mawtaw C', 'Mawtaw B', 'Mawtaw A'],
    ['Sun sungbekin khawl sak thei', 'Khawl sak thei', 'Khawl sak kingah lo'],
    ['Kikhenna giit panin atawm pen metres 2 hal ah mawtaw ki khawlsak(park) thei', 'Kikhenna giit panin a tawmpen metres 3 hal ah mawtaw ki khawlsak(park) thei', 'Kikhenna giit panin a tawmpen metre 1 ciangah mawtaw ki khawlsak(park) thei'],
    ['Ai, N bek maan hi', 'He, N pen hoih pen napi M leh O zong kingah veve hi', 'He, M, N and O a vekin kingah hi'],
    ['A sawi-a(angle) mawtaw park ding cih ciaptehna ahih kei leh akigit a omna munte ah', 'Lampi laizang panin mun awng a zai mahmah na munah', 'Lampi a zai mahmah na ah'],
    ['Horn pia in', 'Dampai inla kidawm mahmahin', 'Na taihatna zah khiam kei in'],
    ['Maan A', 'Maan C', 'Maan B'],
    ['Inn in lampi lang khat liah(block) hi', 'Upmawh bang lo hi', 'lamka lampi kituahnate ah mitawh ki phukha thei hi'],
    ['Dam pai sak semsem in. Na dam pai sak naak leh nang adingin lauhaui lozaw hi', 'Manlang takin setbing makhelh in la, na nunga mawtaw taisan in', 'Hong nawhte awl mawh se kei inla, patau se kei in. A lauhuai lohna mun panin setbing makhelh panin'],
    ['Na tai hatna zahin tai in', 'Mawtaw dangte tawh kiton dingin dampai sakin', 'Veilam lamzing(lane)ah kikhin in'],
    ['Veilam lamzing(lane)ah kikhinin lam awn in', 'Taklam lamzing(lane) ah kikhinin lam awn in', 'Lampi taklam naihah hawlin'],
    ['Na a dingin traffic mei eng ahih manin kihei veve in', 'Khawl inla, meiphelh mawtawpi paisak phot in', 'Meiphelh mawtawpi in hong makhelh loh nadingin hat sakin'],
    ['Lim/Ciaptehna (sign) a kisuang bangbang zui tawntungin', 'Lim/ciaptehan a kisuang bangbang nasep hun sung bek zui in', 'Nasem a om ciang bekin lim/ciaptehna kisuangte zui in'],
    ['Manlang takin khawl pahin', 'Patau mawtaw in hong makhelh dongin veilam lamzing(lane)ah kikhinin', 'Patau mawtaw kimakhelh sak inla, a nungah a naih thei penin zui-in'],
    ['Lampi kituahna na tunma in veilamah kikhin in', 'Na adingin traffic mei eng ahihmanin hawl suak lel in', 'Dampai sak deuh inla, lam na khak loh nadingin khawl a kisap leh khawlin'],
    ['40 km/h sanga hatzaw lo kidawm takin hawlin', 'Khawl inla, meitaang a khawl dong ngakin', 'Mei a taang sungin bus makhelh in'],
    ['Lampi mei om lohna lampite bekah', '80 km/h sanga hatzaw tai theihna lampi khat peuhpeuh ah', 'Lampi khat peuhpeuh ah, lampi mei aom phial zongin'],
    ['Na mawtaw mei tang lela(high beam) sa-in nusia in', 'Khe tawh lampaina ah mawtaw khawlsakin', 'Hong kimuh theih nading mun teel in ahih kei leh hazard mei taangsak kawmin'],
    ['Mawtaw maante en inla lamzing(lane) laih in', 'Dampai sak in', 'Hat sakin, a manlangthei bang penin peel in'],
    ['A dam tai mawtawte makhelh nadingin taklam nehin tai in', 'A awmg zawzaw ah na tai ding hi', 'Mi makhelh ding na hih kei buangleh veilam khenah/lamzinah na tai ding hi'],
    ['Taklam khen/lamzin pen mawtaw dangte pelhna ding hi', 'Taklam khen/lamzin pen patau mawtaw te aa ding hi', 'Taklam khen/lamzin(right lane) pen kimakhelh nadinga kikoihcing hi'],
    ['Khawl inla, meitaang a phia a khawl dong ngak in', 'Meitang a phiat sungin bus makhelh in', 'Kidawm in, naupang om kha ding hi'],
    ['He, hazard mei taang sakin tawmvei bek na khawl leh', 'He, mawtaw tungpan na tuah kei naak leh', 'Ai, kingah vet lo'],
    ['Metres 5 akihalna ciang beekah', 'Metres 50 akihalna ciang beekah', 'Metres 20 akihalna ciang beekah'],
    ['Kiphal lo', 'He, ahizongin na khut khat tawh mawtaw hawlna na len ding hi', 'Lampi kituahna ah na khawlsung bek kingah'],
    ['A gamla tai ciang bekin', 'He Kisam', 'Kisam lo, license nei hi limlim pha zo'],
    ['Amau pilvang lo-in lampi thukhun zuilo uh hi', 'Amaute muh hamsa in, mawtaw hawl dangte zahin kikepna/kituamna neilo uh hi', 'Hat pipi in tai uha, a meitaang zang lo uh hi'],
    ['Na tot ding lampi bekah na lungsim khempeuh pia(attention) in', 'Lampi limtakin en denin. Mawtaw gei leh nung etna maante sit den kawmin hong tung thei ding alauhuai te panin pilvangin', 'Lauhuai a om theidingte hong et pih dingin mawtaw tuang dangte hilh in'],
    ['Dampai sak inla, lam kibawlna munah tai suakin', 'Khawl in la, lauhuai na sakkei leh tai suak in', 'Na mawtaw khawl sak inla, lam lakte hong lahna bangin zui-in'],
    ['Khawl in, lamlahna na ngak ding hi', 'Taklam lamzing(right lane)a tai mawtawte mai-ah na tai theih nadingin hatsak in', 'Mi dangte awn kawminla, taklam lamzing(lane)ah kikhin in'],
    ['Mawtaw pualam, a nung leh mai-ah', 'Mawtaw padenpoh maan kidal lo ahih nak leh padenpoh sung mun khat peuhpeuh ah', 'Mun khat peuhah'],
    ['L ahih kei leh P laimal vekpi', 'L ahih keileh P laimal tamzaw', 'L leh P a kikhen theihna ciang'],
    ['Nei lo. Lampi ah a tai simun mawtawte lam awn den ding uhhi', 'Nei lo, khe tawtna bekah tai/hawl ding uh hi', 'Nei mah'],
    ['A maan panin Khe lampai, mawtaw dang leh mawtaw saikel a om hiam cih sit masa ding', 'Mawtaw mai mei a taan leh taan loh sit tel in', 'Tutna kigakna a maanin a om kik hiam cih sit in'],
  ];

  var correctAnswers = 
  [
    'Kal 6 sung test dang na neih ding hong kiphal lo ding',
    'Hong kithuhilh ding a, sum liau leh thongkiat dongin gawtna hong kipia thei hi',
    'A kihel kha khempeuh tungah thu kibawl dinga, sum liau leh thongkiat dongin hong kigawt ding hi',
    'Hilh/sinsak thei lo',
    'Kha 12',
    'Damdam in paisak inla lampi tungah pai kik ding',
    'Lampi veilam naih lamah hawl ding',
    'Veilama emergency lamzing(lane)ah kikhin in',
    'He, kihei ding theihsakna(signal) mei mawtaw-ah a kithuah leh',
    'Dampai sak inla, hong leh pai (nang lama hong tai) mawtawte lam awn dingin kiging in',
    'Kidawm in, akisam zah sangin a gamla zaw leh hun akisapna munte ah kilehhei peuhmah ken',
    'A nung leh mai-ah 1 metre beek hal/hawi ding',
    'kingah vet lo',
    'He, lampi paite aa dingin alauhaui thei leh anawngkai sak thei ahih leh mawtaw kongkhak hong sedah in',
    'Ai, kiphal vet lo',
    'Kingah ngiat lo',
    'Mawtaw mei aniam (low beam) in tangsak ding',
    'Na mai a mawtaw ahih kei leh Nang lam hong zuan mawtaw tawh metres 200 banga na kinaih uh ciang',
    'Dampai sak inla, bus masak sak ding cih om ahih manin bus lam awn in',
    'He, banghun banghun in',
    'Na mawtaw ah datsi, sathau, tui a kicing hiam cih leh na tyre a puak mah hiam cih cian masa in',
    'Pusuak theihna ding(exit) dang na tun masiah tai suak lelin',
    'Na (speed)tai hatna zah',
    'Na kihei ding metre 100 sungah',
    'Kiphal ngiat lo',
    'Mawtaw liante leh inn mawtaw(caravan) a kai mawtaw dangte tawh metres 60 bang peuhmahin kihal in',
    'Kiphal ngiat lo/Kingah ngiat lo',
    'Na mawtaw pei(tyre) huih a dim hiam cih cian masa in',
    'Brake sik inla, na veilamah mun awng en inla, na horn pia kawm sa-in na mei phia sak in',
    'Na tuahsiatna (accident)-na mun uh tawh kinai pen Palik zumah nai 24 sungin na tuahsiatna thu puak pelmawh in',
    'Na license ensak inla, amau ii license(or details) zong maan zaih inla kemin, mawtaw nei te min leh tenna(address)te zong kithei sak un',
    'Kisam bangin huh pah inla cina mawtaw (ambulance) sap nading ma la pahin. Tua khit teh palikte ko in',
    'Meilengte hatin gikuh ahih manin khawl pahpah thei lo uh hi',
    'Lampi gal khat lam a awn kei(block) a leh',
    'Taklamah pial na sawm hun peuhpeuh ciangin',
    'Mawtaw kihal mahmah hun en in la, mawtawte hatna tawh kituakin tai in',
    'Dampai sak inla, lampi ukte lamlahna zui in',
    'Mawtaw khawl ding akikham hunin hih huamah na khawl het kei ding hi',
    'Dampai sak inla, mun zapi awn in',
    'Mawtaw neu(Car) license',
    'Na dinmun na kitheih phetin RTA zasak pah in',
    'Mawtaw na kawm ma-in genbang hi cihna lai panin hawl kiphal/kingah mah ahi hiam cih kancian masa in',
    'Register abei ni a Zingcianga kipan na mawtaw a kipuahphat a, inspection (sittelna) onga, a ki register masiah hawl khia nawn kei in',
    'A tyre val(spare) ahih hangin tyre maatsa(hoihlo) zat pen kiphal lo/daan kalh ahi hi',
    'Nang aa dingin a hoih bekin a tutna khin in',
    'Gan kikhawite phu kha lo-a na khawl pah theih nadingin dampai sak in',
    'Taklam kihei ding ha hih manin na taklam theihsakna mei(right indicator) pia in',
    'Daan/Ngawtna ngah lo ding. Ahangin, traffic mei a san khit nunga a tai suaksuak teitei te bek maan kizaih hi',
    'Kileh kik ding kingah ngiat lo',
    'Naupang tonpih in',
    'Handbrake kaamin, a gear(transimission) "P" ah koih in',
    'Mawtaw C',
    'Khawl sak kingah lo',
    'Kikhenna giit panin a tawmpen metres 3 hal ah mawtaw ki khawlsak(park) thei',
    'Ai, N bek maan hi',
    'A sawi-a(angle) mawtaw park ding cih ciaptehna ahih kei leh akigit a omna munte ah',
    'Dampai inla kidawm mahmahin',
    'Maan A',
    'Inn in lampi lang khat liah(block) hi',
    'Hong nawhte awl mawh se kei inla, patau se kei in. A lauhuai lohna mun panin setbing makhelh panin',
    'Veilam lamzing(lane)ah kikhin in',
    'Veilam lamzing(lane)ah kikhinin lam awn in',
    'Khawl inla, meiphelh mawtawpi paisak phot in',
    'Lim/Ciaptehna (sign) a kisuang bangbang zui tawntungin',
    'Patau mawtaw in hong makhelh dongin veilam lamzing(lane)ah kikhinin',
    'Dampai sak deuh inla, lam na khak loh nadingin khawl a kisap leh khawlin',
    '40 km/h sanga hatzaw lo kidawm takin hawlin',
    'Lampi khat peuhpeuh ah, lampi mei aom phial zongin',
    'Hong kimuh theih nading mun teel in ahih kei leh hazard mei taangsak kawmin',
    'Dampai sak in',
    'Mi makhelh ding na hih kei buangleh veilam khenah/lamzinah na tai ding hi',
    'Taklam khen/lamzin(right lane) pen kimakhelh nadinga kikoihcing hi',
    'Kidawm in, naupang om kha ding hi',
    'Ai, kingah vet lo',
    'Metres 20 akihalna ciang beekah',
    'Kiphal lo',
    'He Kisam',
    'Amaute muh hamsa in, mawtaw hawl dangte zahin kikepna/kituamna neilo uh hi',
    'Lampi limtakin en denin. Mawtaw gei leh nung etna maante sit den kawmin hong tung thei ding alauhuai te panin pilvangin',
    'Na mawtaw khawl sak inla, lam lakte hong lahna bangin zui-in',
    'Mi dangte awn kawminla, taklam lamzing(lane)ah kikhin in',
    'Mawtaw pualam, a nung leh mai-ah',
    'L ahih kei leh P laimal vekpi',
    'Nei mah',
    'A maan panin Khe lampai, mawtaw dang leh mawtaw saikel a om hiam cih sit masa ding',
  ];

}