class IntersectionQuiz {
  var images = ['blank', 'inter2', 'inter3', 'inter4', 'blank', 'inter6', 'inter7', 'blank', 'inter9', 'inter10',
  'inter11', 'inter12', 'inter13', 'inter14', 'blank', 'inter16', 'blank', 'blank', 'inter19', 'inter20',
  'blank', 'inter22', 'inter23', 'inter24', 'inter25', 'inter26', 'inter27', 'inter28', 'blank', 'inter30',
  'inter31', 'inter32', 'inter33', 'inter34', 'inter35', 'inter36', 'inter37', 'inter38', 'blank', 'inter40',
  'inter41', 'inter42', 'inter43', 'inter44', 'inter45', 'inter46', 'inter47', 'inter48', 'inter49', 'inter50',
  'inter51', 'inter52', 'blank', 'blank'];

  var questions = [
    'Lam kituahna/lamkabom na tunkuan ciangin vei leh taka mawtaw taite na sit ding hi',
    'Lam kituahna/lamdabom ah traffic sign hi taleh signal lak bangmah omlo hi. Tua munah tai suak na sawm leh',
    'Hih taka lam kituahna/lamkabom-ah taklam na kawi ding ciangin',
    'Hih a nuaia danin T-lamkituahna(T-intersection) ah taklamah kihei nuam hi lecin na vei leh taka mawtawte na awt a kul mah hiam?',
    'Accident hang peuhin KHAWL(Stop) leh LAM AWNIN(Give way) cih ciaptehna kilakhia/kisuang lo hi mah leh, lampi gitte in khiatna a nei uh hiam?',
    'Lam kituahna-ah na kihei ciangin khe tawh lampaite lam na awn ding hiam?',
    'Lamkituahna na tun ciangin na pai sawmna na maiah mawtaw na dim khin hi. Bang cih ding na hiam?',
    'Lamzing(lane) omna te ah na tai ciangin, Taklam ah akawi ding hile cin koi lamzing(lane) panin kawi ding',
    'Hih a nuaia limah mawtaw O leh mawtaw P ten lamkituahna a lut ma un, LAM AWNIN(Give Way) cih ciaptehna (signboard) hong tuak uh hi. Koi mawtaw pai masa zaw ding?',
    'Mawtaw O pen ah KHAWL(stop sign) cih ciaptehna om hi',
    'Hih limsung pan mawtaw P leh O te in taklamah kawi ding uh hi, veilama X tawh a kiciamtehna ah kawi dingin koi mawtaw dinmun hoih pen hiam?',
    'Hih limsungah lamkituahna-ah khe lam kanna om hi. Lamkituahna ah KHAWL(stop sign) ciaptehna zong om hi. Khe lampaite awn in na khawl khin hi. Stop line gitah na khawl kik ding a kisam hiam?',
    'Lamkituahna muna LAM AWMIN(Give Way) cih ciaptehna in',
    'Hih lim sunga koi mawtaw penin lam awn ding hiam?',
    'Veilamah na kawi nuam hi. Veilamah kawi ding cihlahna mei(left indicator) bang hunah zang ding',
    'Hih a nuaia T-lamkituahna-ah koi mawtaw in lam awn ding hiam?', 
    'Lampi langkhat lam bekah pai thei(one way) ah, thaltang lim ciaptehna lah omlo, tua lampi(one way) panin taklamah na kawi nuam hi, na mawtaw koi lam neh sak ding?',
    'Lampi ah teipi/thaltang lim ciaptehna(arrow marked) a om loh ciangin koi panin veilamah kihei ding',
    'Meileng lam tawh a kikim lamkanna(level crossing) ah KHAWL(stop sign) cih kisuanna na tun ciangin bang cih ding na hiam?',
    'Hih limsung a mawtaw neu na hawl hi',
    'Lampi tawh kikim meileng lamkanna(level crossing) ah lamdalna(boomgates) kikhakta a, theihsakna(signal) mei phia ta hi', 
    'Lampi tawh kikim meileng lamkanna(level crossing) ah hih lim kisuang na naih ciangin',
    'Lampi tawh kikim meileng lamkanna(level crossing) ah meileng hong pai ding cih theihsakna mei(signal) ataan loh hangin', 
    'Hih limsunga lamkituahna a zuan mawtaw sungah na om hi',
    'Sydney khuapi sunga lamkituahna ah na om laitakin meileng neute hong lut sawm a leh',
    'Mataw tam mahmah na lamkituahna mun nazuan a, na kaantan nuam hi. Lampai-lak mei (traffic light) zong a eng(green) hong taang hi. Bang hun ciangin lamkituahna na lut ding hong kiphal hiam?',
    'Mawtaw tam mahmah na lamkituahna-ah damtaka pai mawtawte lakah na om a, tai suaka lamkaan ding suak ding na ut hi. Lampai-lak mei(traffic light) hong eng(green) ciangin',
    'Hih lamkituahna langkhat lama mawtawte a khawl uh hi. Hih limsunga mawtaw sungah na om a, lamkituahna na kaantan nuam hi. Lampai-lak mei(traffic light) zong eng(green) hi. Bang cih ding na hiam?',
    'Hih a nuai-a thute lakah koi pen maan/dik (correct) hiam?',
    'Lamkituahna na lut laitakin mei a naipak(yellow) hong taan leh',
    'Hih meite a taan/phiat(flashing) ciangin, bang deihna hiam',
    'Hih takah veilamah na kawi sawm hi. Khelampaite  mei a san(red) laitak hi',
    'KHAWL(stop sign) ciaptehna omna lamkituahna na tung hi. Khawlna ding mun ciaptehna akigit omlo hi. Koi takah khawl ding na hiam?',
    'KHAWL(stop sign) ciaptehna omna lamkituahna omna mawtaw A ah na oma, taklamah kawi ding na ut hi. Nang lam hong nga mawtaw B kiangah zong KHAWL(stop sign) ciaptehna om a, veilamah kawi nuam hi. Kua pai thei masa zaw ding hiam?',
    'Hih lamkituahna in lampai-lak mei(traffic light) ahi a, ciaptehna(sign) bangmah nei lo hi. Mawtaw A ah na om a, taklamah na kawi nuam hi. Bang hun ciangin pai thei ding na hiam?',
    'Lampai-lak(traffic light) mei ahih kei leh ciaptehna(sign) a nei lo lamkituahna na tung hi. Tai suak dingin bangci khensat ding na hiam?',
    'Hih lamkituahna ah lampai-lak(traffic light)mei ahih kei leh ciaptehna(sign) omlo hi. "A" tawh a kiciamteh mawtaw sungah na om hi. Veilamah na kawi nuam hi. Bang cih ding na hiam?',
    'Mawtaw A ah na om a, hih lamkituahna panin taklamah na kihei nuam hi. Nang hong maingat mawtaw B zong taklamah kihei nuam hi. Koi lampi(path) tawn ding na hiam?',
    'Palik lam makaite lamkituahna(intersection) ah lamlakin a om ciangun',
    'Mawtaw A ah na om a, taangtakin na taisuak ding hi. Kua in lam awn zaw ding?',
    'Hih roundabout panin veilamah kawi na ut hi. Koi lamzing(lane) na zangthei tam?',
    'Taklam lamzing(right lane)ah na tai a, hih roundabout panin taisuak (pial lo)ding na ut hi. Bang hun ciangin roundabout nuasia dingin veilam lahna mei taang sak ding na hiam?',
    'Roundabout panin veilamah na kihei ding ciangin',
    'Hih roundabout ah lam pial lo-in na tai suak nuam hi. Hih a nuai-a thute sung panin koi pen maan hiam?',
    'Hih roundabout panin veilamah na kihei nuam hi. Koi lamzing(lane) zang ding na hiam?',
    'Roundabout panin pial lo-in na taisuak nop ciangin veilam lamzing(left lane) ahih kei leh taklam lamzing(right lane) khat peuhpeuh panin na lut thei hi. Roundabout ah na tai sungin',
    'Roundabout panin veilam na kihei/pial ding ciangin lamkualna(Roundabout)',
    'lamzing(lane) nih omna roundabout-ah na taisuak nuam hi, koi lamzing(lane) tawn zaw ding na hiam?',
    'Hih roundabout tawnin mawtaw saikel tuangnu/pa tai suak nuam hi. Mawtaw saikel tuangnu/pa in hih a kiciamteh mawtaw hangin a kidawp mahmah kul ding hi, ahang pen',
    'Hih roundabout panin nong paina lampi mahah kileh kik dingin',
    'Lamzing(lane)nih omna hih roundabout-ah a kiciamteh mawtaw pen taklamah a kawi thei ding hiam?',
    'Mawtaw san penin taklamah kawi in roundabout nusia nuam hi. Hi dana kihei na dingin mawtaw omna lamzing(lane) a maan mah hiam?',
    'Lampi ukte aom na lamkituahna/lamka bom na lut ciangin',
    'Lamkituahna lamka-bom na kihei nading lamah khe tawh lamkaan na mu hi',
  ];

  var choice = [
    ['Mawtaw pai a tam ciang bekin', 'A tawntungin', 'Stop sign a om te bekah'],
    ['Na veilama mawtawte bek lam na awn ding hi', 'Na taklama mawtawte bek lam na awn ding hi', 'Nang lam hong leh pai taklama kihei sawmte bek lam na awn ding hi'],
    ['Na veilam pana mawtaw hong pai, taklama kihei sawmte bek lam na awn ding hi', 'Mawtaw nang lama hong lehpai(oncoming vehicle) a tang pai suak ding mawtaw or veilama kiheite leh na taklama mawtaw khat peuhpeuh', 'Khe tawh lam paite bek lam awn in'],
    ['He kulmah. A kihei uha, a kihei kei uh zongin', 'Kul lo, nang awt kullo nang right nei', 'Kul lo, taklama mawtawte sim loh'],
    ['Nei lo, na taklama mawtawte bek lam na awn ding hi', 'Nei lo, a kilehhei na hih leh bek lam na awn ding hi', 'Nei mah, ciaptehna(sign)te mah bangin khiatna nei hi'],
    ['Veilam na kihei ciang bekin lam awn ding', 'A lauhuai dinmun ahih leh vei leh takah kihei ding teh khe tawh lampaite lam awn ding', 'Taklamah kihei ciangbekin lam awn ding'],
    ['Lamkituahna ah lutin, na mai-a mawtawte akikhin dong ngak in', 'Na taklamah mawtaw tai a om kei leh tai suak lel in', 'Lamkituahna lampi laizangah na khak lohna dingin lampi a awn dong ngakin'],
    ['Lam zing(lane) mawtaw tawmna pen panin', 'Taklam nawl penpen pan ahih kei leh lamzingtunga thalthang lim taklam akawk omna lamzing khat peuhpeuh panin', 'Veilam lamzing nawl penpen panin'],
    ['Mawtaw O', 'Mawtaw P', 'Kua pai masa zaw cih tung ah kinga hi'],
    ['Mawtaw dang khempeuhin mawtaw O lam awn ding uh hi', 'Mawtaw O in mawtaw R kia/bek lam awn ding hi', 'Mawtaw O in mawtaw P, Q leh R te lam awn ding hi'],
    ['A nih un hoih lo tuak hi', 'Mawtaw P', 'Mawtaw O'],
    ['Na taklamah mawtaw tai a om leh bek khawl ding', 'Khawl teitei ding, a tawntungin', 'Lamkituahna a awng naak leh khawl lo ding'],
    ['Dampai sakin na taklama mawtawte bek lam na awn ding hi cihna hi', 'A tawntungin na khawl cip ding hi cihna hi', 'Alauhuai Kiphut khak theihna dinmun ahih leh mawtaw dang khempeuh lam na awt theihna dingin kigingkhol in cihna hi'],
    ['Mawtaw K', 'Mawtaw J', 'Mawtaw L'],
    ['Na nunglamah mawtaw dang a om leh', 'A tawntungin', 'Lampi-ah teipi/thalthang lim ciaptehna a om ciang bekin'],
    ['Tua mun a tung nunung zawzaw in', 'Mawtaw Q', 'Mawtaw R'],
    ['Lampi laizangah', 'Lampi taklam ah', 'Lampi veilamah'],
    ['Lampi ii koi lam koi lam panin kingah', 'Lampi laizang panin', 'Lampi ii veilam nawl pen na panin'],
    ['Khawl in la, pai ding a lauhuai loh ciangbekin lamkan in', 'Lamkanna ah meileng a na om leh bek khawl in', '10 km/h in dampai sak inla, lamkan in'],
    ['Mawtaw dang a om kei phial zongin na khawl ding hi', 'Mawtaw dang tawh kiphut khak ding lauhuai ahih leh bekin na khawl ding hi', 'Na veilam maw na taklam hiam khatah mawtaw a om ciang bekin khawlin'],
    ['Meileng hong pai na muh kei leh lamkaan dingin na kipan thei hi', 'Lamdalna(gate) a kikhai toh a, theihsakna(signal) mei a mit khit ciang bekin lamkaan na kipan thei pan hi', 'A kikhak gate kiimah damtaka na pai theih leh na kaan pan ding hi'],
    ['Dampai sakin, na vei leh tak lam panin meileng hong pai leh pai loh en in la, a kisap banga khawl thei dingin kiging khol in', 'Na hatngei zah khiam loin kaan suakin', 'Meileng hong pai khatpeuh na pelh theih nadingin hatsak zaw semin'],
    ['Hat sakin meileng lam manlang takin na kaan ding hi', 'A khawl pah thei dingin dam paisak in, kiphut khak ding lauhuai ahih leh lam awn in', 'Khawl bikbek in'],
    ['Mawtaw dangte in na pai lam hong theih nadingun na mawtaw mei taang sak in', 'Lamkituahna na tun ma-in khawl in', 'Kidawm takin hawl inla, hong dawkvat mawtawte a peel pah thei dingin damtakin hawl in'],
    ['Lamkituahna na kaantan ma-in na totna lamzik/lamzin (lane) laih in', 'Lamkituahna-ah lut inla, ahizongin meileng neu tawh va kisu kha kei in', 'Lamkituahna a awn/asian dong ngakin'],
    ['Na nunga mawtaw in pai dinga signal hong piak teh', 'Lampai-lak mei a eng khit phetin', 'A gallamah lam na kankhiat khit nading mun a awn ciangin'],
    ['Na nunglam mawtawte na khak kei hi cih cian in', 'Na mawtaw a gear koih nadingah na koih hi cih cian in', 'Lamkituahna/lamkabom na khak kei hi cih cian in'],
    ['Lamkituahna ah hawl suak inla, traffic mei a kilaih ma-in a kaan man dingin ki lamen in', 'Lamkituahna kaan khiat khit theihna ding donga lampi a awn dong ngakin', 'Lamkituahna ah hawl inla, na veilamah kihei/kawi/pial in'],
    ['Lamkituahna-a maanzaihnate in lampai-lak mei(traffic light) a san sunga lamkituahna-a kan teitei mawtawte bek maanzaih hi', 'Lamkituahna-a maanzaihnate in lampi-lak mei a naipak(yellow) sunga lamkituahna a kaante bek maan zaih hi', 'Lamkituahna-a maanzaihnate (Red Light Cameras) in hattaka lamkituahna a kaan mawtawte maan zaih hi'],
    ['Na hat sak theih zahin na mawtaw hat sakin', 'Lamkituahna ah tai suaksuak in', 'A khawl pah dingin brake kang in'],
    ['Hih hun sungin hih kiimah khelampaite(pedestrians) kiphal lo hi', 'Khe tawh lam a kaan te khetotna (footpath) lamah kileh kik ding uh hi', 'Khe tawh lam kaan kipan phing lo ding'],
    ['Taklam lamzin(lane)ah kikhin in', 'Khe tawh lam a kaan laite lam awn in', 'Veilam nehin damdamin lamkituahna kaan in'],
    ['Lamkituahna tun nading metres 5 na bang ciangah', 'Lamkituahna nai ah, lah va lutto lianlo na munah', 'Lampi langnih kiciantaka muh theihna ciangah'],
    ['Lamkituahna a tung masa zawzaw', 'Car A', 'Car B'],
    ['Tangtaka tai mawtaw in hong khup khit teh', 'Lamkituahna mun na tun phetin', 'Tangtaka tai mawtaw in hong khup ma-in'],
    ['Mawtaw khempeuhin lamkituahna a nusiat donguh ngak in', 'Dampai sak inla, na taklama mawtawte lam awn in', 'A tung masa peuhpeuh pai thei'],
    ['Dampaisak inla, na taklama mawtaw B lam awn in', 'Mawtaw hawl dangte theih dingin na horn pia in', 'Lamkituahna lut inla, kawi in'],
    ['Mailam tuakpan kipeel ding', 'Mawtaw taite dinmun zui-in a khat zawzaw in', 'Nunglam tuakpan kipeel ding'],
    ['Lam hong lahna bangbangin na zui tawntung ding hi', 'Lampi-lak meite a hoih kik dong ngakin', 'Na hih ngeingeisa bangin lamkituahna kaan in'],
    ['Lamkituahna a tung masa zawzaw in', 'Car B', 'Car A'],
    ['Veilam lamzing(left lane)', 'Lamzing(lane) khat zawzaw', 'Taklam lamzing(right lane'],
    ['Point O khup teh', 'Point M khup teh', 'Point N khup teh'],
    ['Kisam na sak ciangbekin theihsakna(indicate) pia in', 'Veilam akipatna pan na kihei siang a tawpdong theihsakna pia in', 'Roundabout na lut khit ciangbekin veilam kihei ding cih theihsakna na pia in'],
    ['Taklam lamzing(right lane) panin lutin veilam lamzing(left lane) ah na pusuak ding hi', 'Roundabout na lutna lamzing(lane) mah panin na pusuak ding hi', 'Veilam lane pan bekin roundabout na nusia tawntung ding hi'],
    ['Lamzing(lane) khat peuhpeuh', 'Lamzing(lane) B', 'Lamzing(lane) A'],
    ['Mawtaw pai a tawmna pen lamzing(lane) ah kisuan in', 'Roundabout na lutna lamzing(lane) mah tawn suak in', 'Na taisuak pah theih nadingin lamzing(lane) laih in'],
    ['Veilam lamzing(lane) panin lutin na pusuak ding hi', 'lamzing(lane) mawtaw tawmna pen panin lutin na pusuak ding hi', 'Taklam lamzing(lane) panin lutin na pusuak ding hi'],
    ['Khat peuhpeuh', 'Taklam bek', 'Veilam bek'],
    ['Thakhat thu in khawl vat thei hi', 'Hat tai lua thei hi', 'Roundabout nusia thei hi'],
    ['Na kihei sungkhempeuh taklam lamzing(right lane) tawnin', 'Na kihei sung khempeuh veilam lamzing (left lane) tawnin', 'Roundabout nusia dingin veilam lamzing(left lane) ah kisuan/lut in'],
    ['Banghun bang hunin kihei thei ding hi', 'Banghun bang hunin kihei thei lo ding hi', 'Taklam lamzing(right lane)ah a kisuan/lut khit ciangin kihei thei hi'],
    ['Maan mah, hih lamzingbek panin kihei/pial thei bek hi', 'Maan lo, roundabout pen taklam lamzingpan bekin a lut ding hi', 'Maaan mah, veilam lamzingpan ahi a, taklam lamzingpan ahi zongin kihei thei'],
    ['Lam ukte theih dingin na horn pia inla, a kihep dinguh lamen in', 'Lam ukte lamlahna zui-in', 'Lamkituahna/Lamka-bom ah khawl inla, dam takin pai in'],
    ['Khe lamkaanpa/nu na phutkhak loh nadingin thakhatin kihei vatin', 'Khe lamkaanpa/nu a kihep theih nadingin na horn pia/ging sak in', 'Khe lamkaanpa/nu lam awn in'],
  ];

  var correctAnswers = 
  [
    'A tawntungin',
    'Na taklama mawtawte bek lam na awn ding hi',
    'Mawtaw nang lama hong lehpai(oncoming vehicle) a tang pai suak ding mawtaw or veilama kiheite leh na taklama mawtaw khat peuhpeuh',
    'He kulmah. A kihei uha, a kihei kei uh zongin',
    'Nei mah, ciaptehna(sign)te mah bangin khiatna nei hi',
    'A lauhuai dinmun ahih leh vei leh takah kihei ding teh khe tawh lampaite lam awn ding',
    'Lamkituahna lampi laizangah na khak lohna dingin lampi a awn dong ngakin',
    'Taklam nawl penpen pan ahih kei leh lamzingtunga thalthang lim taklam akawk omna lamzing khat peuhpeuh panin',
    'Mawtaw P',
    'Mawtaw O in mawtaw P, Q leh R te lam awn ding hi',
    'Mawtaw O',
    'Khawl teitei ding, a tawntungin',
    'Alauhuai Kiphut khak theihna dinmun ahih leh mawtaw dang khempeuh lam na awt theihna dingin kigingkhol in cihna hi',
    'Mawtaw J',
    'A tawntungin',
    'Mawtaw R',
    'Lampi taklam ah',
    'Lampi ii veilam nawl pen na panin',
    'Khawl in la, pai ding a lauhuai loh ciangbekin lamkan in',
    'Mawtaw dang a om kei phial zongin na khawl ding hi',
    'Lamdalna(gate) a kikhai toh a, theihsakna(signal) mei a mit khit ciang bekin lamkaan na kipan thei pan hi',
    'Dampai sakin, na vei leh tak lam panin meileng hong pai leh pai loh en in la, a kisap banga khawl thei dingin kiging khol in',
    'A khawl pah thei dingin dam paisak in, kiphut khak ding lauhuai ahih leh lam awn in',
    'Kidawm takin hawl inla, hong dawkvat mawtawte a peel pah thei dingin damtakin hawl in',
    'Lamkituahna a awn/asian dong ngakin',
    'A gallamah lam na kankhiat khit nading mun a awn ciangin',
    'Lamkituahna/lamkabom na khak kei hi cih cian in',
    'Lamkituahna kaan khiat khit theihna ding donga lampi a awn dong ngakin',
    'Lamkituahna-a maanzaihnate in lampai-lak mei(traffic light) a san sunga lamkituahna-a kan teitei mawtawte bek maanzaih hi',
    'Lamkituahna ah tai suaksuak in',
    'Khe tawh lam kaan kipan phing lo ding',
    'Khe tawh lam a kaan laite lam awn in',
    'Lamkituahna nai ah, lah va lutto lianlo na munah',
    'Car B',
    'Tangtaka tai mawtaw in hong khup khit teh',
    'Dampai sak inla, na taklama mawtawte lam awn in',
    'Dampaisak inla, na taklama mawtaw B lam awn in',
    'Mailam tuakpan kipeel ding',
    'Lam hong lahna bangbangin na zui tawntung ding hi',
    'Car B',
    'Veilam lamzing(left lane)',
    'Point O khup teh',
    'Veilam akipatna pan na kihei siang a tawpdong theihsakna pia in',
    'Roundabout na lutna lamzing(lane) mah panin na pusuak ding hi',
    'Lamzing(lane) A',
    'Roundabout na lutna lamzing(lane) mah tawn suak in',
    'Veilam lamzing(lane) panin lutin na pusuak ding hi',
    'Khat peuhpeuh',
    'Roundabout nusia thei hi',
    'Na kihei sungkhempeuh taklam lamzing(right lane) tawnin',
    'Banghun bang hunin kihei thei lo ding hi',
    'Maan lo, roundabout pen taklam lamzingpan bekin a lut ding hi',
    'Lam ukte lamlahna zui-in',
    'Khe lamkaanpa/nu lam awn in',
  ];

}