
class NegligenceQuiz {
  var images = ['blank', 'blank', 'blank', 'neg4', 'blank', 'blank', 'blank', 'blank', 'blank', 'neg10',
  'blank', 'neg12', 'neg13', 'neg14', 'blank', 'blank', 'blank', 'neg18', 'neg19', 'neg20',
  'neg21', 'blank', 'blank', 'blank', 'blank', 'neg26', 'blank', 'blank', 'blank', 'blank'];

  var questions = [
    'Mawtaw khawlna kim-ah mawtaw na hawl ciangin',
    'Lamkawi ahih kei leh mualneu tung lam na zuan hi. Mi makhelh dingin lampi laizang git kaan kei in',
    'A lauhuai lo thei pena lampi kawcik tawnin mualdawn zuat dan pen',
    'Hih a nuaiate-ah sim loh, lamzin(lane) khat bek omna lampi (lima bangin)ah mawtaw dangte a taklam uhah na makhelh tawntung ding hi',
    'Mawtaw dang na makhelh ciangin na makhelh mawtaw mai-ah nungkik ngei kei in',
    'Na nunga mawtaw in hong makhelh nuam cih theihsakna(signal) hong pia hi. Bang cih ding na hiam?',
    'Na mai-a mawtaw a hat tai semsem leh',
    'Na mai-a mawtaw na makhelh nadingin bang tan kisam hiam cih na tel kei leh',
    'Nang hong kimakhelh ciangin bangci huh thei ding na hiam?',
    'Manta color mawtaw (purple vehicle) ah na om a, na mai-a mawtaw na makhelh thei kha ding hi',
    'Mawtaw dang makhelh ding na kipat ma-in',
    'A KIHEI DING MAWTAW MAKHELH KEI IN cih kisuanna mawtaw saupi (a lim kilak bangin) nungah na tai hi. Tua mawtaw saupi-in veilamah kawi ding ci-in theihsakna (signal) lak hi.',
    'Setbing tuang/sik mipa/minu (pedal cyclist) bangci makhelh ding na hi hiam?',
    'Nang hong makhelh mawtaw in na mai-ah hong kikhiin ding cih hong theihsak leh',
    'Mi na makhelh ma-a na hih ding a masa penin',
    'Na license in a kiphal zah sanga sangzaw na sisanah zuu a muh manin, thu hong kikhen ciangin na license na taan theih banah,',
    'Lauhuai taka mawtaw na hawl na hangin hong kimawhpaih/thu hong kikhen (convicted) leh',
    'Veilam lamzinah na tai a, lamkituahna (intersection) panin taklamah kihei/pial/kawi na ut hi. Lamzin (lane) taklamah kikhiin a, na nunga mawtaw hawlin horn hong pia hi. Bang hih khial na hiam?/Bang hihkhialh nei na hiam?',
    'Hih mawtaw hawlpa/hawlnu in daan(upadi) phalloh leh a awlmawh loh a sep/hih bang hiam?',
    'Hih lampi-a taihat theih zah (speed limit) pen 90 km/h hi. Veilam lama om mawtaw khat na makhelh lian hi. A banah bang hih ding na hiam?',
    'Hih lampi-a taihat theih zah (speed limit) pen 100 km/h hi. Bang hun ciangin taklam lamzin (lane) zang thei ding na hiam?',
    'Na taklam panin mawtaw dang khatin hong makhelh hi. Bang na cih leh mawtaw thukhun palsat (traffic offense) na hi hiam?',
    'Palikte in mawtaw kitaih te lakah a kihel dingin hong upmawh uh hi leh a kilawm bangin daan hong pia pah thei uh hi. Hih a nuaia-te sung panin koi pen man hiam?',
    'Lampi ah mawtaw hat na kidemna hangin ahih kei leh a nihveina mawhpaihna na tuah leh, hih a nuaia gawtnate lakpanin koi pen hong kipia ding hiam?',
    'Lampi ah mawtaw hat na kidemna hangin ahih kei leh mawhpaihna na tuah leh, hih a nuai-a gawtnate lak pan koi pen hong kipia ding hiam?',
    'Na mai-a Mawtaw makhelh dinga na kithawi laitakin taklam theihsakna mei (right indicator) taang na mu hi',
    'Lampi a kibawlna munte ah na hatsak manin hong kimat leh',
    'Tawlkhat sungbek aa dinga Lampi kibawlna munte ah mawtaw na hawl ciangin',
    'Mawtaw lampi-ah na lut ciang ahi zongin, Mawtaw lampi pan pai khiat ciang ahi zongin',
    'Taihatzah ding palsatna (speeding offense) hangin na P1 license pen hun ciangtan sung khat hong kikhak sak(suspended) ding hiam?',
  ];

  var choice = [
  ['Mawtaw ki park te hong pai khia ding cih signal pia ahih kei leh mawtaw kawm lak panin naupang hong tai khia vat a om hiam cih encik in', 'Mawtaw hawl dangte hong paikhiat loh nadingun na horn pia inla, na mawtaw mei taang sakin', 'Taklam signal hong kipia na muh leh khawl in'],
  ['Na mailam 75 metres ciang kiciantaka na muh theih kei leh', 'Na mailam 100 metres ciang kiciantaka na muh theih kei leh', 'Nang lam hong leh zuat mawtaw taite kician taka na muh theih kei leh'],
  ['Damdamin veilam bekah paiin', 'Na speed khan inla, horn pia-in', 'Nang lam hong zuan mawtawte kidawp thei nadingin headlight taang sakin'],
  ['Mawtaw dang pen nang sanga a dampai zawk teh', '80 km/h sanga hatzaw-a na tai ciang', 'Mawtaw dang pen taklamah a kawi ciang'],
  ['Nang lam zuanin mawtaw hong lehpai hong kilang vat ahih kei buang leh', 'Na mawtaw nunglam etna maan panin na makhelh mawtaw mu thei nahih buang kei leh', 'Na makhelh mawtaw hawlpa in makhelh dingin hong thei-sak (signal) ahih buang kei leh'],
  ['Hong hattai lua ahih leh na nunga om lai dingin theisakna(signal) pia in',  'Hong makhelh theihlohna dingin hatsak in', 'Veilam neh in tai-inla kimakhelh sakin'],
  ['Na makhelh nadingin hun tawm zaw kisam hi', 'Na makhelh nadingin hun a tam zaw na kisam hi', 'Na makhelh ma-in na naih tektek ding hi'],
  ['Mawtaw a gear khiam in la, hatsakin (speed up)', 'Makhelh nadingin hun hoih ngak in', 'Na mai-a mawtaw hawlpa/nu damtak a apai nadingin horn pia in'],
  ['Veilamah kikhin inla, khawl in', 'Hong makhelh theih nadingin manlang takin brake siik in', 'Veilamah neh inla, mawtaw dang hong lut theih nadingin mun awng sak in'],
  ['Mawtaw ii veilam leh taklam koi zawzaw panin', 'Mawtaw ii taklam pan bekin', 'Bang hun bang hunin'],
  ['Makhelh nadingin mun za zaw na neih theih nadingin theisakna (signal)pia-in dam tai-in', 'Lauhuai lo hi cih cian in la, a kisap leh gear laihin na makhelh sawm lam theihsak in', 'Horn pia-inla kihei-in makhelh in'],
  ['Lampi veilamah kikhiin in,mawtaw sau na peel thei hi', 'Mawtaw sau na kihei masa sak ding hi', 'Mawtaw sau na peel thei hi, bang hang hiam cih leh lamzin (lane) laizang panin veilamah a kawi thei kei hi'],
  ['Setbing tuang/sik mipa/minu lampi panin a kihep khiat nadingin horn pia in', 'Setbing tuang/sik mipa/minu na naih theih bangpenin va naih in, tua hileh amah kihemin nang hong kimakhelhsak ding hi', 'Mawtaw dangte na makhelh bangin kidawm takin makhelhin'],
  ['Hatsak in la, tua mawtaw na mai-ah lutsak kei-in', 'Ama a ding mun awn dingin dam tai dingin kiging in', 'Hong makhelh mawtaw muh dingin na mawtaw mei taangsakin'],
  ['Horn pia in', 'Lauhuai lo hi cih leh nanglam hong zuan mawtaw omlo hi cih cianin', 'Speed khanin'],
  ['Na taihat theih zah dingin hong kiciangtan sak thei hi', 'Automatic mawtaw (vehicle) hawl hong kikhaam thei hi', 'Thawngah hong kikhum thei hi'],
  ['Hoih lohna demerit point kia hong kipia thei hi', 'Sum hong kiliau sakin hoih lohna (demerit point) hong kipia thei hi', 'Na license na taan thei a, thawng sungah hong kikhum thei hi'],
  ['Dam tai lua', 'Lamzin (lane) khenna git paisuak(unbroken line) kaantan', 'A kisam lopi-in lamzin (lane) khek/kheng'],
  ['Lamzin(lane) khek/laih dingcih theisak lo', 'Lamkawina-a git-paisuak(unbroken line) kaantan', 'Lamnawl khetawtna lam pana mi makhelh'],
  ['Hih lamzin (lane)ah om suakin', 'Veilam lamzin (lane)ah kikhin in', 'Mawtaw khatzaw nusia dingin hatsak inla, hih lamzin (lane) mahah taisuak in'],
  ['Mi makhelh ciang bekin ahih kei leh taklamah kihei/pial/kawi ding ciang bekin', 'Na kiimah mawtaw dang a om loh ciangin', 'Na ut hun peuh ciangin'],
  ['Na taklama mawtaw dang a om laitaka na hatsak leh', 'Na taklama mawtaw dang om laitaka na dampai sak leh', 'Na taihat zah kibanga/laih lo-a na tai leh'],
  ['Palikte in na mawtaw hong matsakin kha thum sung hong kepsak thei uh hi', 'Palikte in na mawtaw hong laksakin lilaam/lilaan zuak thei uh hi', 'Palikte in tua muna palik-zum (local police station)ah na mawtaw hong laksakin, zingsang dong hong kepsak thei uh hi'],
  ['Na mawtaw hong laksakin kizuak kha thei ding hi', 'Na mawtaw zumah na ciamteh(register) thei nawn kei ding hi', 'Na mawtaw hong kepsak man na liau kul kha thei hi'],
  ['Kidawm nading warning lai hong kipia in, na liau ding hi', 'Demerit point thum hong khiam in, sum tampi hong liau sak ding hi', 'Sum tawmkhat hong kiliau sakin demerit point khat hong khiam ding hi'],
  ['Na mawtaw maan en inla, a nungah dampai kik in', 'Brake pahin la, khawl in', 'Na pelh theih nadingin manlangin takin hatsakin'],
  ['Na hatsak manin liau sum leh demerit point na sum thei hi', 'Lam bawlna-a speed limit-te pen lamlahna bek ahih manin gawtna (penalty) bangmah na ngah kei ding hi', 'Kidawm dinga theihsakna (warning) lai hong kikhak ding hi'],
  ['Lampi awng (mawtaw tai dang om lo) leh na hatngei zah mahin tai suakin', 'Dam pai sak inla, a lauhuai (hazard) a om hiam cih khuahekin', 'Horn pia in'],
  ['Lampi-a omte theihsak nadingin in horn pia-in', 'Khawl in la, mawtawte bek lam awn in', 'Setbing tuangte, mawtaw leh khe-a paite lam awn in'],
  ['Ai, hilo', 'He, hi mah', 'Taihat theihzah ciangtanna (speed limit) sanga 10 km/h a hatzawk leh bek'],
  ];

  var correctAnswers = 
  [
    'Mawtaw ki park te hong pai khia ding cih signal pia ahih kei leh mawtaw kawm lak panin naupang hong tai khia vat a om hiam cih encik in',
    'Nang lam hong leh zuat mawtaw taite kician taka na muh theih kei leh',
    'Damdamin veilam bekah paiin',
    'Mawtaw dang pen taklamah a kawi ciang',
    'Na mawtaw nunglam etna maan panin na makhelh mawtaw mu thei nahih buang kei leh',
    'Veilam neh in tai-inla kimakhelh sakin',
    'Na makhelh nadingin hun a tam zaw na kisam hi',
    'Makhelh nadingin hun hoih ngak in',
    'Veilamah neh inla, mawtaw dang hong lut theih nadingin mun awng sak in',
    'Mawtaw ii taklam pan bekin',
    'Lauhuai lo hi cih cian in la, a kisap leh gear laihin na makhelh sawm lam theihsak in',
    'Mawtaw sau na kihei masa sak ding hi',
    'Mawtaw dangte na makhelh bangin kidawm takin makhelhin',
    'Ama a ding mun awn dingin dam tai dingin kiging in',
    'Lauhuai lo hi cih leh nanglam hong zuan mawtaw omlo hi cih cianin',
    'Thawngah hong kikhum thei hi',
    'Na license na taan thei a, thawng sungah hong kikhum thei hi',
    'Lamzin (lane) khenna git paisuak(unbroken line) kaantan',
    'Lamkawina-a git-paisuak(unbroken line) kaantan',
    'Veilam lamzin (lane)ah kikhin in',
    'Mi makhelh ciang bekin ahih kei leh taklamah kihei/pial/kawi ding ciang bekin',
    'Na taklama mawtaw dang a om laitaka na hatsak leh',
    'Palikte in na mawtaw hong matsakin kha thum sung hong kepsak thei uh hi',
    'Na mawtaw hong laksakin kizuak kha thei ding hi',
    'Demerit point thum hong khiam in, sum tampi hong liau sak ding hi',
    'Na mawtaw maan en inla, a nungah dampai kik in',
    'Na hatsak manin liau sum leh demerit point na sum thei hi',
    'Dam pai sak inla, a lauhuai (hazard) a om hiam cih khuahekin',
    'Setbing tuangte, mawtaw leh khe-a paite lam awn in',
    'He, hi mah',
  ];

}