
class PedestrainQuiz {
  var images = ['blank', 'ped2', 'blank', 'ped4', 'ped5', 'ped6', 'blank', 'blank', 'blank', 'blank', 
  'blank', 'blank', 'blank', 'ped14', 'ped15', 'ped16', 'ped17', 'ped18', 'ped19', 'ped20',
  'blank', 'ped22', 'ped23', 'ped24', 'ped25', 'blank', 'ped27', 'blank'];

  var questions = [
    'Khe tawh paite lamkanna kiciaptehna-ah khe tawh paite na awn ding hi',
    'Khe tawh paite lamkaanna kiciaptehna zuanin na pai a, lamkaan kuanmah a na om kei leh',
    'Khangkhamte ahi a, naupangte in ahi zongin lam hong kaan uh leh',
    'Lampi tunga lim kigelhte lak panin koi penin mai-ah khetawh lamkanna om cih hong hilh/theisak hiam?',
    'Na mai-a mawtaw khelam-kaanna ah nakhawl hi.', 
    'Sangnaupangte lamkaanna lamlakpa/nu in hih dan ciamtehna (sign) atawi na muh ciangin',
    'Hih a nuaia thute sung panin koi man hiam? Setbing tuangte (bicycle riders) in',
    'Lampi ngei-a naupang kimawl or lampai te kiang nai-a mawtaw na hawl ciangin',
    'Zu in a khoihkhak/buaisak/Zukham khe tawh a paite',
    'Khe tawh lamkaana, lamkituahna (intersection), ahih kei leh sanginn lamkaannate kimah mawtaw na hawl ciangin', 
    'Mi tamna mun (gentehna. bus khawlna mun)te ah mawtaw na hawl ciangin',
    'A kipark/kikhawlsak mawtawte (parked vehicles) te lak napai ciangin hih a nuai-ate sung panin koi pawimawh pen hiam?',
    'Khuasia nuai-ah (wet weather) mawtaw na hawl ciangin',
    'Khe tawh lamkaanna-a traffice mei a san khit ciangin mei-am color (amber light) hong phiat teh',
    'Hih a nuaia thute lakah koi maan hiam?',
    'Hih mite lamah mawtaw na hawl hi. Bang hih/cih ding na hiam?',
    'Na mai-ah a kawi akigit a kiciamteh na mu hi. Bang cihna ahi hiam?',
    'Lampi tunga hih ciaptehna in',
    'Mi khatin lam akaan laitak na zuan hi.', 
    'Khe tawh Lamkaanna mun na zuan a, hih limsung-a dan na mu hi',
    'Khe tawh Lamkaanna mun na zuan a, hih limsung-a dan na mu hi',
    'Khe tawh Lamkaanna mun na zuan a, hih limsung-a dan na mu hi',
    'Khe tawh lamkaanna na zuan a, hih limsung-a dan na mu hi.',
    'Khe tawh Lamkaanna mun na zuan a, hih limsung-a dan na mu hi',
    'Khe tawh Lamkaanna mun na zuan a, hih limsung-a dan na mu hi',
    'Khe tawh a paite taih thei dinmunah na om leh lam awn in. Mei tang ginalo ah mawtaw na hawl ciangin',
    'Tram khawlna-a a khawl meileng neu kiang dongah mawtaw na hawl hi. Na hih/sep ding pawimawh pen bang hiam?',
    'Khe tawh lampaite lam na awn ding hi',  
  ];

  var choice = [
    ['Kiphutkhak ding lauhuai ahih leh', 'Na veilam pan bekin lam hong kaan uh ciangin', 'Na taklam pan bekin lam hong kaan uh ciangin'],
    ['Dam paisak(slow down) in khawl dingin kiging in', 'Hatsak in, lamkaan hong om kha leh', 'Na kaan ma-in khawlin'],
    ['Amau na nawh nadingin horn na piak kul kha ding hi', 'Luahuai lo takin a kaan theih nadingun hunsau zaw na ngak kul kha ding hi', 'Mawtaw dangte na nawngkaisak loh nadingin amau na pelh kul kha ding hi'],
    ['C', 'A', 'B'],
    ['Khelam-kaanna ah lamkaan a om kei leh na makhelh thei hi', 'Mawtaw khawl pen na makhelh kei ding hi', 'Mawtaw hong leh pai a om kei leh na makhelh thei hi'],
    ['Naupangte in lam a kaan siang dong uh leh ciamtehna a kikhiat dong na ngak ding hi', 'Naupangte na muh theih nawn loh dongin na ngak ding hi', 'Naupangte in lamkaanna taklam a phak dongun na ngak ding hi'],
    ['Mawtaw tamna lampi-ah tuang thei lo uh hi', 'Lampi ki-ukna thukhun a zuih ding uh hi', 'A kimuh theih nadingun mawtaw tai lohna lamah tai/tuang ding uh hi'],
    ['Na hatngei bangin hatsak lel inla amau peel in', 'Na om lam a theih nadingun horn pia in', 'Dam hawl in la, a khawl pah thei dingin kiging in'],
    ['Lampi gei-ah hong pai dinguh uphuai lo ahih manin awlmawh kul lo hi', 'Lampi-a tuahsiatna a tungsak pipen te ahi uh hi', 'Zu dawn khit ciangin kidawm/pilvang zaw uh ahih manin a dawnlo khe tawh a paite sangin lauhuai lo zaw uh hi'],
    ['Dampai sak tawntung ding, khe tawh lamkaan om hiam cih enin, a khawl pah thei dingin na kiging den ding hi', 'Na taihatna zah kilahna (speedo) na en tawntung/den ding hi', 'Lamzin veilam (left lane)-ah na kihem den ding hi'],
    ['Na phut khak loh nadingin mawtaw na hatsak pelmawh ding kisam hi', 'Hong kimuh cian theih nadingin na mawtaw mai mei tangsak lela ding kisam pelmawh hi', 'Dampai sak inla, lampi ah hong lut vat khak dinguh en in'],
    ['Taklam lamzin (right-hand lane) a om leh taklam lamzin (right-hand lane)-ah pai ding', 'Khe tawh a pai mi, ganhing leh mawtaw kongkhak kihong a om leh om loh en ding', 'Na mai-a mawtaw tawh a kinaih thei penin pai in'],
    ['khawl ding in, piteek/puteek lamkaante huh ding', 'Khe tawh apai te tui na theh khak loh nadingin lampi laizang tawnin', 'Khe tawh a pai mite hong kinawh vat thei ahih manin amaute hoih tak en in'],
    ['Traffic mei-te kisia cihna hi a, khe tawh a paite in khe tawh lamkaanna zang lo ding cihna hi', 'Khe tawh a pai mite tawh kitaih ding a lauhuai kei nak leh kidawmtakin lamkaanna-ah hawl/tai suak thei cihna hi', 'A eng hong kidawk ding ahih manin hong kidawk masiah kikhin kei-in'],
    ['Lamkaanna ding a kiciaptehna munte bekah khe tawh a paite na awn bek ding hi', 'Khe tawh a paite in lampi tungah thu (special rights) nei tuan lo uh hi', 'Khe tawh a paite na phut khak ding a, a lauhuai leh amau lam awn phot in'],
    ['Na taihatna (speed) zah mahin tai inla, horn pia in', 'Amau sukha/phukha thei ding nahih manin khawl inla amau lam awn in', 'Lamkaanna kimkhat ciangdong a tun dong uh mawtaw dampai sak inla, tua panin hawl suak in'],
    ['Lamkaanna ah khe tawh a pai om le om loh enin kidawm in', 'Na mai-a lampi naal (slippery) ahih manin kidawmin', 'Lampi gei-ah ganhing a om leh om loh enin'],
    ['Mawtaw kipark theihna mun cihna hi', 'Khe tawh apaite in thu (special rights) a neihna mun hi cihna', 'Special Speed Limit kizatna mun cihna hi'],
    ['Mawtaw dampai sak inla, a kinawh theih nadingin horn pia in', 'Na taih/phu khak loh nadingin na mawtaw hawl dampai sak ahih keileh khawlsakin', 'Na speed ngeimah tawh mipa kimkotah kihei vatin'],
    ['Mawtaw dampaisak inla, naupangte lam awnin hawl suak in', 'Mawtaw dampai sak inla, lamlakpa in ciaptehna (sign) a lakkhiat dong na khawl (stop) ding hi', 'Na taina lamzin (lane) a siang dongin khawlin naupangte na ngak ding hi'],
    ['Khawl inla, khe tawh apaite in lam a kaan siang dong uh leh mei eng (green light) hong taan dong na ngak ding hi', 'Khawl inla, khe tawh a paite in lam a kaan khit uh teh na tai/hawl zawm kik ding hi', 'Mawtaw hawl dampai sak inla, khe tawh a paite lam na awn ding hi'],
    ['Mipa tawh kiphut khak ding lauhuai ahih leh mipa lam na awn ding hi', 'Mawtaw dangte na khak khak loh nadingin na taihatna speed zah kem in', 'Mawtaw dampai sak inla, mipa a kilehkik nadingin na horn pia in'],
    ['Naupangte\' lamkaanna (children\'s Crossings)ah uliante lamkaan dingin lam na ot/awt kul lo hi', 'Khe tawh a paite in a kiciamteh lamkaannate bek panin lampi kaan ding uh hi', 'Khe tawh a paite tawh a lauhuai kiphuttuah kha ding nahih manin lam na awn ding hi'],
    ['Na speed 5 km/hr in na khiam ding hi', 'Thahatin hong tai vat thei uh ahih manun na mawtaw dampai sak inla na kidawm mahmah ding hi', 'Amaute na awlmawh kei ding a, nunglam etna maan (rear vision mirror) kia ngaihsakin'],
    ['Na naih mahmah masiah hong mu thei lo uh ahih manin na mawtaw dampai sak inla, na kidawm mahmah ding hi', 'Horn pia-in na tai ngeina zahin tai in, tua hileh mawtaw dangte na nawngkai sak kei ding hi', 'Mawtaw dangte a paisuak theih nadingin amah makhelh in'],
    ['Na mawtaw mei (headlight) a tang thei bangpenin tangsak den/tawntung in', 'Khe tawh paite muh hamsa uh ahih manin limtakin amaute om leh om loh en in', 'Khe tawh a paite tawh na kigamlat theih nadingun taklam lamzin (right hand lane) ah tai den/tawntung in'],
    ['Nang langkhat lam panin nanglamah mawtaw hong leh tai a om hiam cih limtakin encik in', 'Kidawm pha mahmah kawmin mawtaw dam hawl inla, khe tawh a paite lam awn in', 'Mawtaw hawl dangte na ziakaisak loh nadingin na mawtaw damdam in hawl suak in'],
    ['A kiciamteh (marked) khe tawh lamkaanna munte leh traffice mei-a khe tawh lamkaannate bekah', 'A kiciamteh (marked) khe tawh lamkaanna munte bekah', 'Khe tawh lamkaanna ciamtehna a om kei zongin khe tawh apaite na phutkhak theih ding zaha lauhaui ahih leh a tawntungin lam na awn ding hi'],
  ];

  var correctAnswers = 
  [
    'Kiphutkhak ding lauhuai ahih leh', 
    'Dam paisak(slow down) in khawl dingin kiging in',
    'Luahuai lo takin a kaan theih nadingun hunsau zaw na ngak kul kha ding hi',
    'B',
    'Mawtaw khawl pen na makhelh kei ding hi',
    'Naupangte in lam a kaan siang dong uh leh ciamtehna a kikhiat dong na ngak ding hi',
    'Lampi ki-ukna thukhun a zuih ding uh hi',
    'Dam hawl in la, a khawl pah thei dingin kiging in',
    'Lampi-a tuahsiatna a tungsak pipen te ahi uh hi',
    'Dampai sak tawntung ding, khe tawh lamkaan om hiam cih enin, a khawl pah thei dingin na kiging den ding hi',
    'Dampai sak inla, lampi ah hong lut vat khak dinguh en in',
    'Khe tawh a pai mi, ganhing leh mawtaw kongkhak kihong a om leh om loh en ding',
    'Khe tawh a pai mite hong kinawh vat thei ahih manin amaute hoih tak en in',
    'Khe tawh a pai mite tawh kitaih ding a lauhuai kei nak leh kidawmtakin lamkaanna-ah hawl/tai suak thei cihna hi',
    'Khe tawh a paite na phut khak ding a, a lauhuai leh amau lam awn phot in',
    'Amau sukha/phukha thei ding nahih manin khawl inla amau lam awn in',
    'Lamkaanna ah khe tawh a pai om le om loh enin kidawm in',
    'Khe tawh apaite in thu (special rights) a neihna mun hi cihna',
    'Na taih/phu khak loh nadingin na mawtaw hawl dampai sak ahih keileh khawlsakin',
    'Mawtaw dampai sak inla, lamlakpa in ciaptehna (sign) a lakkhiat dong na khawl (stop) ding hi',
    'Khawl inla, khe tawh apaite in lam a kaan siang dong uh leh mei eng (green light) hong taan dong na ngak ding hi',
    'Mipa tawh kiphut khak ding lauhuai ahih leh mipa lam na awn ding hi',
    'Khe tawh a paite tawh a lauhuai kiphuttuah kha ding nahih manin lam na awn ding hi',
    'Thahatin hong tai vat thei uh ahih manun na mawtaw dampai sak inla na kidawm mahmah ding hi',
    'Na naih mahmah masiah hong mu thei lo uh ahih manin na mawtaw dampai sak inla, na kidawm mahmah ding hi',
    'Khe tawh paite muh hamsa uh ahih manin limtakin amaute om leh om loh en in',
    'Kidawm pha mahmah kawmin mawtaw dam hawl inla, khe tawh a paite lam awn in',
    'Khe tawh lamkaanna ciamtehna a om kei zongin khe tawh apaite na phutkhak theih ding zaha lauhaui ahih leh a tawntungin lam na awn ding hi',
  ];

}