
class TrafficLightLaneQuiz {
  var images = ['blank', 'tll2', 'tll3', 'tll4', 'blank', 'blank', 'tll7', 'tll8', 'tll9', 'tll10',
  'blank', 'blank', 'tll13', 'tll14', 'tll15', 'tll16', 'tll17', 'tll18', 'tll19', 'tll20',
  'tll21', 'tll22', 'tll23', 'tll24', 'tll25', 'blank', 'blank', 'blank', 'blank'];

  var questions = [
    'Freeway na lut ciangin mawtaw tai dangte tawh bangci taikhawm/paikhawm/kigawm ding',
    'Hih tatzia tuamtuam kilakte lakah purple (manta-color) Mataw in koi teng hih thei hiam?',
    'Hih tatzia tuamtuam kilakte lakah purple (manta-color) Mataw in koi teng hih thei hiam?',
    'Hih tatzia tuamtuam kilakte lakah purple (manta-color) Mataw in koi teng hih thei hiam?',
    'Lampi kikhenna git nih a paisuakt (double unbroken dividing line)te kigit hi',
    'Khua neu lampi git nih paisuak tawh a kikhenna (double unbroken dividing lines) ah na tai hi. Lampi panin lutna ding inn huang leh lampialna ding bangmah om lo hi. Hih lampi kikhenna git nihte na pelh/kaan ding hong kiphal hiam?',
    'Hih limsunga bangin lampi khenna (lane)te ah mawtaw na hawl a, na totna lamzin (lane) na laih thei hi',
    'Lamzin(lane) nih hong kigawm ciangin (hih anuai lim bangin), kua in lam awn ding?',
    'Hih lim en leng, mawtaw koi penin lam awn ding hiam?',
    'Theihsakna mei(signal indicator)te bang hunah zang ding na hiam?',
    'Pautau mawtaw(emergency) te pautau ging na zak ciangin',
    'Mawtaw A na hawl hi. Mawtaw B makhelh nuam na hih manin',
    'Lampi hi danin kiciamtehin na mai-ah mawtaw a tai bangmah om kei ta leh, setbing makhelh dingin git na kaan ding hong kiphal mah hiam?',
    'Lampi hi-danin kiciamteh ta leh, git kaanin mi na makhelh ding a kingah hiam?',
    'Mi makhelh dinga na kithawi laitakin na mai-a git a tawng (dividing lines) pen git-nih-paisuak(unbroken line) tawh hong kilaih na mu hi. Bang cih ding na hiam?',
    'Hih lam-kituahna panin veilamah pial/kihei na ut hi. Lamnawl gitna lam-kituahna ciangah kigit tang tosuak hi. Veilam ah kawi ding a kiphal mah hiam?',
    'Lane na laih ma-in',
    'Transit lane T2 rule kizatna lane te ah mawtaw na hawl hi. Passenger khat tawh minih na pha uh hi. Tua transit lane ah na hawl ding hong kiphal mah hiam?',
    'Transit lane T3 rule kizatna lamzin(lane)ah na kisuan kha hi. Hih lamzin(lane) ah mawtaw tai dang om lo hi. Passenger khat bek nanei hi. Bang cih ding na hiam?',
    'T2 kilaihna lamzin(lane) na zuan hi. Mawtaw sungah nang bek na om hi. 200 metres na a om lamka-bom/lamkituahna (intersection) panin veilamah na kawi nuam hi. Hih transit lane ah na hawl thei mah diam?',
    'Y tawh a kiciamteh mawtaw sungah na om a, lam laizang lamzin (median lane) tawnin taklamah na kawi nuam hi. Mawtaw O tawh kiciamteh pen, lam laizang lamzin (median lane) tawnin nang lam zuanin hong dam tai a, kihei ding cih kilangsak hi. Hih lam-laizang lamzin (median lane)-ah lutin kihei/kawi/pial ding hong kiphal mah hiam?', 
    'Mawtaw na hawl a, passenger khat na la nuam hi. Na khawl nopna lamzin (lane) pen BUS taina lamzin (BUS LANE) ahi hi. Tua sanah na khawl ding hong kiphal mah hiam?',
    'Hih ciaptehna/lim (sign) in bang cihna hiam?',
    'One-way lampi (street) panin taklamah na kihei/kawi/pial nuam hi. Koi mun panin kihei ding na hiam?',
    'Mawtaw dang makhelh dingin ngaihsutna pan khensatna maan neih kul hi. Hih a nuai-a thute sung panin koi pen maan hiam?',
    'Speed limit 80 km/h kiciamtehna lamzin(lane) tampi anei lampi ah na tai/mawtaw na hawl ciangin koi lamzin(lane) teel ding na hiam?',
    'Theihsakna (signalling) piak pen',
    'Mawtaw lampi(Motor way) ah bangci lut ding na hiam?',
  ];

  var choice = [
    ['Mun awng(gap) en in la, mawtaw tai dangte taihatna zah tawh hatin lutin', 'Khawl phot in la, manlang takin mawtaw dangte lakah lutin', 'Hat sak in la, mawtaw tai dangte lakah kihen in'],
    ['P bek/kia', 'O leh P kia/bek', 'O, P and Q '],
    ['O, P and Q', 'P bek/kia', 'O leh P kia/bek'],
    ['P bek/kia', 'O leh P kia/bek', 'O, P and Q'],
    ['U-turn dingin na kaan thei hi', 'Na mai-a mawtaw a lauhuai kei leh makhelh dingin na kaan thei hi', 'A lauhuai kei nak leh inn huangsung leh mawtaw paina-ah lut dingin hih giitte na kaan thei hi'],
    ['Setbing sikte makhelh nadingin kikaan thei hi', 'Mawtaw dang khat makhelh nadingin kikaan thei hi', 'Bang bang ahi zong Kikaan thei ngiat lo hi'],
    ['Khek/Laih ding cih lahna na piak naak leh khuahek loin na laih thei hi', 'laih ding a lauhuai loh hun ciang bekin na laih thei hi', 'Mawtaw hawl dangte theihsakna in horn na piak nakleh na laih thei hi.'],
    ['Taklam lamzin (lane)a mawtaw in banghang hiam cih leh aman makhelh sawm ahih manin', 'Mawtaw  hat zawzaw in', 'Lamzin (lane line) zikna/gitna a kaan ding mawtaw in'],
    ['Mawtaw B', 'Kuamah in, lampi kigawmtuahna ah ki-awt zia zuih ding dan om lo hi', 'Mawtaw A'],
    ['Lamkawi na tun ding ciangin', 'Na totna lamzin(lane) na laih ding ciang ahih kei leh veilam hiam taklam hiamah na kihei ding ciang', 'Mawtawkhawlna ah na park thuah ding ciang'],
    ['Mi dangte theihsakna in na mawtaw mai mei tang sakin', 'Pautau mawtawte lam na awt theih bangbangin lam na awn ding hi', 'Pautau mawtaw na pelh theih nadingin hat sakin'],
    ['A lauhuai kei leh bek lampi ki-git kaanin makhelh in', 'Lampi khenna kigit paisuak pen kaanin na makhelh ding hi', 'Mawtaw B veilam lamzin(lane) ah a kisuan mateng a nungah ngakin'],
    ['He, lampi pen one-way ahi nak leh', 'He', 'Kiphal lo'],
    ['Na mailamah mawtaw om lo ahih leh kingah', 'He, kingah', 'Ai, kingah lo'],
    ['Makhelh dingin tai suak inla, mawtaw mai-ah a manlang thei bangpenin tai in', 'Makhelh ding na kipat laiin git kitawng(broken line) hi lai ahih manin makhelh dingin tai suak lel in', 'Git-nih-paisuakte ah makhelh kiphal lo ahih manin makhelh nawn se dah in'],
    ['Kingah ngiat lo', 'He, lampi dang ah lut ding ahih kei leh pusuak dingin lamnawl ciaptehna git na kaan thei hi', 'He, taxi hiam, mawtaw kikawm hiam, bus hiam khat tuang na hih leh ahih kei leh tua vengah teeng na hih nak leh'],
    ['Signal sawtvei pi pia inla, mawtaw dang a om hiam cih na maante panin sitphot in','Second nih taang beek signal pia in la, manlang takin lane kheel in', 'Lane danga mawtawte sangin a hat zaw dingin hatsak in'],
    ['Na mawtaw sungah mi nih tuang nahih manun kingah hi', 'Transit lane ah na hawl ding  kingah hi, ahi zongin 250 metres ah veilamah na pial/kihei ding hi', 'Passenger khat bek nei nahih manin transit lane panin na kihemkhia pah ding hi'],
    ['Veilamah kihei in khawl pah in. Tua khitteh, lamzin (lane) dangah kisuan theih madong ngakin', 'Mawtaw dang om lo ahih manin T3 lamzin (lane) ah taisuak in', 'Mihing nih bek tawh T3 lamzin (lane)ah tai kingah lo ahih manin  a lauhuai loh peuhpeuh hun ciangin lamzin(lane) dangah laih pahin'],
    ['Nai cik sung bek pai ding kisam lai nahih manin na hawl thei hi', 'Na hawl suak thei kei hi. A hangin, veilama nakawi nopna lamka-bom/lamkituahna(intersection) pen metres 100 bang bek hileh na hawl thei bek hi', 'Na nunglamah mawtaw dang a om kei nak leh na hawl suak thei hi'],
    ['He, ahi zongin damtakin khawl dingin na kiging ding hi', 'He, ahi zongin mawtaw khat zaw sanga kihei nading mun na tun masak zawk kul ding hi', 'Lam-laizang kiheina lamzin(lane) ah mawtaw dang om khin ahih manin zang kei in'],
    ['Na ut tantan BUS LANE ah na khawl ding hong kiphal hi', 'Passenger la in na taikhiat pah leh BUS LANE ah na khawl thei hi', 'Mataw ki-kawm ahih kei leh taxi hawl na hih buang kei leh BUS LANE ah na khawl ding kingah/kiphal lo hi'],
    ['Meileeng neute aa ding bek lamzin(lane) om hi', 'Meileeng hong pai ding ahih manin dampaisak in la, a khawl dingin kiging in', 'Bus bek taina lamzin (lane) na zuan hi'],
    ['R mun panin. Lampi taklam naih theih zah penin', 'M mun panin. Lampi laizang panin', 'Kihei/kawi/pial ding a lauhuai kei nak leh koi mun peuh panin kihei in'],
    ['Na mawtaw makhelh ding a hat leh, na makhelh nadingin agamlatna a kisam zah tawm pah hi', 'Na nunga mawtaw in hong makhelh sawm ciangin hat tai semsem pen hoih penin lauhuai lo pen hi', 'Mawtaw sau leh golte akihei a om hiam cih na etcian kul hi'],
    ['Mi makhelh ding na hih kei leh veilam lamzin(lane) teel in', 'Veilam or Taklam lamzin khat peuhpeuh', 'A dam tai mawtawte pelh nadingin taklam lamzin(lane) teel in'],
    ['T-lamkituahna (T-intersection) ah na kihei ciangin kisam lo hi', 'Kihei hiam lamzin(lane) laih/nakhek peuhpeuh ciangin piak ding kisam den hi', 'Traffic mei-a green arrow (teipi eng) kipiahna ah kihei/kawi/pial ciangin theihsakna (signalling) piak kul lo hi'],
    ['Mun awng (gap) a om leh om loh en in la, a om leh hatsak inla mawtaw dangte tawh kitonin kidawm takin lutin', 'Khawl phot in la, tua khitteh manlang takin lutin', 'Dam tai in la, mawtaw dangte lakah kihen in'],
  ];

  var correctAnswers = 
  [
    'Mun awng(gap) en in la, mawtaw tai dangte taihatna zah tawh hatin lutin', 
    'O leh P kia/bek',
    'O, P and Q',
    'O leh P kia/bek',
    'A lauhuai kei nak leh inn huangsung leh mawtaw paina-ah lut dingin hih giitte na kaan thei hi',
    'Bang bang ahi zong Kikaan thei ngiat lo hi',
    'laih ding a lauhuai loh hun ciang bekin na laih thei hi',
    'Lamzin (lane line) zikna/gitna a kaan ding mawtaw in',
    'Mawtaw B',
    'Na totna lamzin(lane) na laih ding ciang ahih kei leh veilam hiam taklam hiamah na kihei ding ciang',
    'Pautau mawtawte lam na awt theih bangbangin lam na awn ding hi',
    'Mawtaw B veilam lamzin(lane) ah a kisuan mateng a nungah ngakin',
    'Kiphal lo',
    'Ai, kingah lo',
    'Git-nih-paisuakte ah makhelh kiphal lo ahih manin makhelh nawn se dah in',
    'He, lampi dang ah lut ding ahih kei leh pusuak dingin lamnawl ciaptehna git na kaan thei hi',
    'Signal sawtvei pi pia inla, mawtaw dang a om hiam cih na maante panin sitphot in',
    'Na mawtaw sungah mi nih tuang nahih manun kingah hi',
    'Mihing nih bek tawh T3 lamzin (lane)ah tai kingah lo ahih manin  a lauhuai loh peuhpeuh hun ciangin lamzin(lane) dangah laih pahin',
    'Na hawl suak thei kei hi. A hangin, veilama nakawi nopna lamka-bom/lamkituahna(intersection) pen metres 100 bang bek hileh na hawl thei bek hi',
    'He, ahi zongin damtakin khawl dingin na kiging ding hi',
    'Mataw ki-kawm ahih kei leh taxi hawl na hih buang kei leh BUS LANE ah na khawl ding kingah/kiphal lo hi',
    'Meileeng neute aa ding bek lamzin(lane) om hi',
    'R mun panin. Lampi taklam naih theih zah penin',
    'Mawtaw sau leh golte akihei a om hiam cih na etcian kul hi',
    'Mi makhelh ding na hih kei leh veilam lamzin(lane) teel in',
    'Kihei hiam lamzin(lane) laih/nakhek peuhpeuh ciangin piak ding kisam den hi',
    'Mun awng (gap) a om leh om loh en in la, a om leh hatsak inla mawtaw dangte tawh kitonin kidawm takin lutin',
  ];

}