
class VictoriaSpecificQuiz {
  var images = ['1', 'blank', '3', '4', 'blank', 'blank', 'blank', '8', 'blank', 'blank',
  '11', 'blank', 'blank', '14', 'blank', '16', 'blank', 'blank', 'blank', '20',
  '21', '22', '23', 'blank', '25', 'blank', '27', '28','29', '30',
  'blank', 'blank', 'blank', 'blank', 'blank', '36', '37', 'blank', '39', '40',
  '41', 'blank', 'blank', '44', '45', '46', 'blank', '48', '49', '50', 
  'blank', 'blank', '53', '54', '55', 'blank', 'blank', '58', '59', 'blank',
  'blank', 'blank', '63', '64', '65', 'blank', 'blank', '68', '69', '70',
  '71', 'blank', '73', 'blank', 'blank', 'blank', 'blank', '78', '79', 'blank',
  '81', 'blank', 'blank', 'blank', 'blank', '86', 'blank', 'blank', '89', '90',
  '91', 'blank', '93', '94', 'blank', 'blank', '97', '98', 'blank', '100',
  '101', '102', '103', 'blank', '105', '106', 'blank', '108', '109', '110', 
  'blank','blank', 'blank', '114', 'blank', '116', 'blank', 'blank', 'blank', '120', 
  '121', '122', 'blank', 'blank', '125', '126', '127', '128', '129', 'blank',
  '131', 'blank', '133', 'blank', '135', '136', '137', '138', '139', '140',
  '141', '142', '143', 'blank', 'blank', '146', '147', 'blank', '149', 'blank',
  '151', '152', 'blank', 'blank', 'blank', 'blank', 'blank', '158', '159', '160',
  'blank', '162', '163', '164', '165'];

  var questions = [
    'Mawtaw A hawl hi le cin, kua pen lam awn ding',
    'Mawtaw hawl cin a, bus lane ah kihei dingin lut kul ta a, tua bus lane na tot theih zah sau pen bangzah hi ding hiam?',
    'Mawtaw A a hawl hi le cin, Koi zaw lam na awt kul ding',
    'Mawtaw A a hawl hi le cin, kua\'n lam ong awn ding',
    'Lampi laizangah a kaang tawh a kigiit gual nih om ta leh, na mai-a mawtawte makhelh nadingin tua giit nihte kaan/pelh theih mah na hiam?',
    'Mawtaw hawl siam i cih te\'n a tuah dinguh genkholh thei uh hi. Tua banga theihna/siamna bangci ngah uh hiam?',
    'Tuah siat theihna (hazard) thei khol i cih bang hiam?',
    'Mawtaw A leh Mawtaw B hibangin kitaih uh a, a kitaihna hang uh pen',
    'Mawtaw hawl ta dingin ihmut suahna pen bang hunin haksatna pi suak thei hiam?',
    'Mawtaw brake a kingah loh cianga na hih teitei ding khat bang a hiam?',
    'Mawtaw A hawl hi le cin, hih bang hunah bangci kikep ding na hiam?',
    'Khat guak beka mawtaw hawl thei nahih theih nadingin, License na nei ma-a na hih ding a thupi pen bang hiam?',
    'A kiphal zah sanga tam zaw na sisanah zuu 1.5 level (BAC) ciang bang om leh, tua bangpi tawh mawtaw hawl lecin nanga dingin mi tawh kitaih theihna bangzah ciang ahi hiam?',
    'Mawtaw A a hawl hi lecin, mataw B tawh na kitaih loh nadingin bangci pelh ding na hiam?',
    'Nai khat sungin tai 100 bang hatin mawtaw tawh na tai laitakin na khawl nopna munah na khawl theih nadingin bang tan vei pan khiam khol(cover) ding?',
    'Hih ciaptehna (Sign) bang cihna hiam?',
    'Kattaya (Sealed road) tung bang hunin naal pen ding hiam?',
    'Inn omna (build-up area) huamah mawtaw hat zahding ciangtanna (speed limit) kisuan lohna munte ah bangzah hat a tai ding?',
    'Lam kawi pan bangci tai khiat ding?',
    'Hih ciaptehna (sign) in a gen pen',
    'Hih ciaptehna (sign) na muh teh bang cih ding?',
    'Na maiah bangci bang lamka om hiam?',
    'Hih lampi ciaptehna in bang gen hiam?',
    'Lampi laizangah git akang dashline (single white broken line) a kizut hi in, Koi lam ah mawtaw hawl ding na hiam?',
    'Na mai-ah lamlak mei hibanga hong tan ciang,',
    'Mai-a mawtaw tawh setkan nih sanga tamzaw bang kihal ding cih bang hun ciang hoih hiam?',
    'A kua zaw-in lam awn zaw ding?',
    'Hih ciaptehna ii khiatna bang hiam?',
    'A taktakin roundabout pan kihei khiat nading in, koi mawtaw pen in signal pia ding hiam?',
    'Hih ciaptehna in mawtaw dang khempeuhin inn omna (build-up areas) munte ah bus-te awn ding uh hiam?',
    'Mawtaw tam mahmahna lakah mawtaw na hawl laitakin taklam a kihei ding na mai-a mawtaw in na lampi ong khak leh',
    'David in a mawtaw ah GPS system zang nuam ahih manin, midang tawh a kitaih khak loh nadingin a lauhuai bangcih khiap ding',
    'Mawtaw hawl tungte in mi tawh ih kitaih khaklohna ding, lauhuai na ih khiap nadingin bang thupi pen hiam?',
    'Mawtaw hawl pen kimawlna tawh kibang kici hi. A hang pen mawtaw hawl leh kimawlna ah',
    'Mawtaw na hawl ciangin banghangin lampi leh a kiim leh paam lim tak et kul ahi hiam?',
    'Mawtaw A na hawl hi. Mawtaw B hawlpa/nu in hong makhelh sawm ta leh bang cih ding na hiam?',
    'Mawtaw A na hawl laitakin tennis ball lampi hong kikhuk leh',
    'Lampi kituahna (lamka bom) na tung ma deuhin traffic light a san (red) hong piah leh bang cih ding na hiam?',
    'Nai khat sungin KM 10 cianga hata tai theih cih banah hih limin bang hong lak lai hiam?',
    'Hih lim in bang hong hilhkhol ahi hiam?',
    'Hih lim bang deihna hi hiam?',
    'Mawtaw a guala ki parkna ah na park a, ahizongin zik kigit kei ta leh, na maia mawtaw tawh bang tanin kihal a park ding na hi hiam?',
    'Na license hong ki phiat/teng (cancelled) sak a leh, Nang pen',
    'Tram meileng a khawlna munah na khawl hi. Khe tawh lampai teng tram tungpan tuakin lam nawl dawhsan (kerb) tung khin zo uh hi. Meileng kongkhakte kikhak khin hi. Bangzah hatna (speed) tawh tua tram(meileng) makhelh thei ding?',
    'Mawtaw A ah na om hi. Mawtaw B in hong pha dekdekin hong zui hi. Bang cih ding na hiam?',
    'Mawtaw A na hawl hi. Kuate lam na awt kul ding',
    'Mawtaw na park nuam hi. Koi lam koi lam panin metre 20 ciangah na park thei kei hi',
    'Na mai-a traffic light-ah a nai-paak-mei (yellow) na taang a, khe tawh lam kan sawma kuamah a na om kei leh bang cih ding na hiam?',
    'A san (red) traffic light a taan leh',
    'Lam zin (lane) ciaptehna om lohna lampi ah mawtaw A na hawl hi. Bang hun ciangin mawtaw B makhelh hong kiphal hiam?',
    'A tunglama khuamtungah lamzin kiciamtehna nei(overhead lane signal) omna lampi-ah mawtaw na hawl hi. A koi lamzin (lane) na tot hong kiphal hiam?',
    'A kisin tung/cil mawtaw hawlte aa dingin zana mawtaw hawl tawh kisai thu hilhna(advice) hoih pen bang hiam?',
    'Hih ciaptehna a nei lampi ah lut ding ahih manin pelmawh na hih ding bang hiam?',
    'Sun sung nasepna hangin na tawl mahmah khin hi. Ahizongin, lam saupi mawtaw na hawl kul ta leh bang cih ding na hiam?',
    'Mawtaw A pen na ki-park khin hi. Tua mun panin na paikhiat ding ciang a tom thei penin theihsakna (signal) piak kisam hiam?',
    'Mawtaw na hawl ciangin a dawklo-mun mawtaw nung (blind spot) te bangcih ding?',
    'A kisin-cil mawtaw hawlte in a tawntungin khensat theihna nei den ding hi',
    'Zanin mawtaw dang khatlamah manawhin mawtaw na hawl hi. Na mawtaw meitang na khiap ma-in bangciangah va naih thei na hiam?',
    'Mawtaw A na hawl a, tangkhial-het-lo (safety tak) in bangci kihei ding na hiam?',
    'Khe tawh lamkanna na tung dek tak a, khuadak vet loin mi khatin khe tawh lam hong kan hi. Na kitaih loh nadingun kua-in mawhpuakna nei zaw?',
    'Tram paina kan tanin taklamah na kihei nuam hi. Tua laitakin tram paina-ah tram na om ta leh, bangci ding na hiam?',
    'Na mawtaw mai-ah tram na khawl hi. Khe tawh tram tungpan tuakin na mai-ah lam kan dingin ngak uh hi. Koici khawl ding?',
    'Freeway-ah hih ciaptehna na kheng hi. Tollway pai nuam lo nahih takteh bangcih ding na hiam?',
    'Mawtaw A na hawl hi. Nang lam zuanin mawtaw hong tai om lo hi. Hih limgelh(diagram) te sung panin a koipenah kimakhelh ding kiphal hiam?',
    'Naupangte\' lamkanna (Children Crossing) ah khawl hi teh. Na mai-ah khe tawh lamkan om uh hi. Bang hun ciangin pai ding hong kiphal hiam?',
    'Gate ahi a, meitaang a phelep hi ta leh a omlo meileng lamkan tanna ah hong kikhawl sak hi. Meileng khat na tai khin lian ta leh bangcih ding na hiam?',
    'Lampi ah sakol hon khat na tuah ciangin bangcih ding?',
    'Koi mawtaw penin lam kituahna (lamka bom) kaan masa pen ding?',
    'Lam zik khatah saikel khat tawh na tai khawm hi. Na kikal/kihalna a tawm pen bangzah hi ding?',
    'Mawtaw A na hawl hi. Freeway na luh ding takteh bang hih ding na hiam?',
    'Mawtaw A na hawl hi. Bang hun ciangin na taklamah kihei thei ding na hiam?',
    'Round-about ah na lut ding teh kuate lam na awn masa ding na hiam?',
    'Mawtaw A na hawl hi. Koi pen lam na awn pelmawh ding?',
    'Hih nate sung panin koi penin mawtaw hawlte ihmut-suak-sak (drowsiness) pen hiam?',
    'Mawtaw kihawl a taangpi in lamdang sak ding hi lo." Banghang in?',
    'Mawtaw hawl kisinte aa dingin mawtaw hawl ciaptehna laibu neih manpha mahmah hi, a hang pen',
    'A taktaka mawtaw hawl a hamsat mahmahna khat pen',
    'Lam kan dingin koi kigualhdan maan pen hiam?',
    'Mawtaw A na hawl hi. Bang hih ding na hiam?',
    'Mawtaw hawl kisinte in a siamna uh behlap nadingin',
    'Mawtaw A na hawl hi. Hih bang hunah bang na cih tam?',
    'Janelle in P1 probationary license ciang bek nei hi. Lamgei ah pial khia napi-in a mawtaw khawl sak lo hi. A hih dinga kiphal lo bang hih hiam?',
    'Na mawtaw tyre a keh/kitap ciang',
    'Nai 120 sung mawtaw hawl sinna neite in license a ngah khit uh teh amau sanga kisinna hun tawm nei zawte sangin a lauhuai tatkhialh theihna bangzahin tawm nei zaw uh hiam?',
    'Peter pen mawtaw hawl a sin lai khat hi. Mai kal sungah nai 5 sung bang kisin nuam hi. Ama adingin a koi dan manpha pen ding hiam?',
    'Bang hun ciang bekin hih a naipaak gitnih (double yellow line) te kantan hong kiphal bek hiam?',
    'Mi tawh kiphu kha hi teh. Palikte hong huh dingin om lo uh hi. Mi a liam om zen zen leh bang na hih tam?',
    'Kua pen tangkhial/mi tawh kitaih kha baih pen ding hiam?',
    'Hih ciaptehna in bang hong hilh hiam?',
    'Hih ciaptehna gei, a koi lam a koi lamah bang hun ciangin nai thum sung mawtaw park ding hong kiphal hiam?',
    'Lampi a na tai laitakin na tunga khuam tungah ciaptehna hong kilah a leh bangcih ding na hiam?',
    'Leihawm(tunnel) sungah na tai laitakin na mawtaw engine gin hong maan kei leh bangcih ding?',
    'Bus sungpan a tuak ding mi khat bus khawlna mun ah mawtaw khat tawh na ngak hi. Koi mun pen in ngakna dingin hoih pen hiam?',
    'Khua sung bus khawlna ah bus khat khawl hi. Bus in taklamah kihei dingin, a nunglam mei (signal) hong piak na mu hi. A cih nopna bang hiam?',
    'Mawtaw tai hatna (speed limit) 110 km/h cianga taina ding lampi ah na tai hi. Bangci lecin na datsi (fuel) nem thei pen ding hiam?',
    'Lampi keu na ah 50 km/h hatin na tai hi. Na khawl ding mun na tun ma 35 metres bang pan na dam pai sak kul hi. Lampi kawtna te ah bang tan pan dam pai sak kul ding hiam?',
    'Mawtaw A na hawl a, lampi panin na pial khia hi. Khe lampaite hong pai ciang koi cih lam awn ding?',
    'Hih ciaptehna/lim in meileng lam tawh kituak lamkanna lim ahi hi. I phawk ding a kisam pen',
    'Meileng lam kan dingin na kithawi a, meileng nasemte khatin khawl ding hong cih hangin meileng hong tai bangmah na mu kei hi. Bang cih ding?',
    'Hih ciaptehna/lim ii deihna bang hiam?',
    'Hih ciaptehna/lim ii deihna bang hiam?',
    'Bang hun ciangin mawtaw A talklam ki-hei (turn right) ding kiphal hiam?',
    'Hih lim/ciaptehna in koi penin hilhcian pen hiam?',
    'Victoria state sungah inn om lohna (outside built-up areas) ah speed limit sign a om lohna lampite ah bangzah a hat sak ding?',
    'Mawtaw A na hawl hi. Na mai-a hong paikhiat sawm setbing tuang khat tawh na kiphu dektak hi. Hih dana kiphuk khak theihna ih pelh theih nadingin',
    'Tram khawlmunah hong khawl laitakin hih bangdan in na hawl hi. Bangcih ding na hiam?',
    'Kalista in a mawtaw sungah GPS thuah hi. Bangci leh mawtaw hawl kawmin GPS zat kiphal bek hiam',
    'Hih mawtaw khawlte sung panin a koi penin khawl dan maan pen hiam?',
    'Mawtaw A na hawl a, koi pen lam na awt kul hiam?',
    'Hih a nuaia thugelhte sung panin a koi penin hih lim/ciaptehna gen hiam?',
    'Mawtaw hawl lai tak "lu tawh encian (head check)"cih bang cihna hiam?',
    'Hithei hi leh mawtaw hawl sin cilte sin hun sung ding pen',
    'Na tawl mahmah laitakin mawtaw na hawl hi. Lampi bangtan sau tai khin na hiam cih na theih loh lam na kiphawk vat hi. Bang hih ding na hiam?',
    'Mawtaw A na hawl a, taklamah na kihei nuam hi. Mawtaw B zong veilamah kihei dingin signal mei pia sak hi. Bangcih ding na hiam?',
    'Ziin/Kongzing tampi omna lampi (multi lane freeway) ah mawtaw na hawl hi. Transit lane om lo hi. Bang hun ciangin taklam kongzing(lane) ah tai hong phal hiam?',
    'Koi mawtaw penin khe lampai pen awn ding hiam?',
    'Zu na dawn ciangin na sisan sunga zu om zah (BAC) na theithei takpi mah hiam?',
    'Lampi tang khatah taihat zah ding (speed limit) sanga 10 km/h-a niam zaw in na tai/hawl hi. Na mai-a mawtaw tawh second nih bang bekin na kihal uh hi. Na mai-a mawtaw na naih tohna hang pen',
    'Lamngei pan kongzing/lamzing (lane) ah na lut hi. Na taikhiat ma-in bangtan vei theihsakna (signal) pia ding na hiam?',
    'Mawtaw A na hawl hi. Koi mawtaw na awt pelmawh kul hiam?',
    'Hih limte sung panin koi pen mawtaw A in mawtaw B lam awt kul hiam?',
    'Koi mawtaw penin hih signboard omna munah van guangin, van khia thei hiam?',
    'Mawtaw a U-turn peuhmah in lam awn ding hi', 
    'Freeway ah lampi pan pialkhiat/pusuakna bangci lut ding?',
    'Mawtaw A na hawl hi. Koi lam tawn ding na hiam?',
    'Hih lim/ciaptehna in hih munah mawtaw na khawl/nga (park) thei ding',
    'Mawtaw A na hawl a, lampi panin na paikhia hi. Horn cikciang pia ding na hiam?',
    'Mawtaw A in Tram khawlna safety zone a va naih semsem ciangin bangci ding hiam?',
    'Mawtaw A na hawl hi. Hih lampi speed limit pen 100 km/h hi. Bang hun ciangin hih lamzing/kongzing (lane) ah hawl ding hong kiphal hiam?',
    'Lampi gei-ah na mawtaw kisia leh, bang cih ding na hiam?',
    'Mawtaw A ah na om hi. Lamzing nih ciaptehna om loin kisutuah/kigawm (lane merge) hi. Koi takah kigawm suk ding na hiam?',
    'Lampi gei-ah mawtaw na khawl sak hi. Lampi panin metre 3 bek na kihalsak hi. Koi lampi ziikin lehngatin mawtaw khawl(park) hong phal hiam?',
    'Monday pan Friday nai 3:30 pan nai 6:30 kikal hih lim/ciaptehna(sign) in bang cih nopna hiam?',
    'Mun muanhuaina(safe place) ah na mawtaw hawl siamna na test(etkhiat) na ding a hoih bang hiam?',
    'Koi mawtaw pai masa pen ding hiam?',
    'Bang hunah mawtaw A in mawtaw B lam awn ding hiam?',
    'Mawtaw A na hawl hi. Kua in lam awn ding?',
    'Koi mawtaw in lam awn ding?',
    'Mawtaw A na hawl hi. Koi mawtaw lam awn ding na hiam?',
    'Hih mawtawte in veilamah kihei dingin om ciat uh hi, koi mawtaw penin a maanin roundabout zuan hiam?',
    'Mawtaw A na hawl hi. Veilamah na kihei nuam hi. Lam kituahna(lamkabom) bangci zuat ding na hiam?',
    'Mawtaw A na hawl hi. Na khawl(park) a, mawtaw taina lampi ah na lut sawm hi. Kua pen lam awn ding na hiam?',
    'Koi mawtaw tot lampi in hoih/lauhuai lo pen hiam?',
    'License na lak ma-in nang hong makaih/hong sinsak mawtaw hawl tawh',
    'Mawtaw hawl khat na hihna tawh siam semsem na hih lam koi ci kigen theih ding hiam?',
    'Na mai-ah lambawl nasemte khatin hih lim/ciaptehna hong laak leh bang cih ding na hiam?',
    'Hibangin mawtaw B leh mawtaw C kiphu kha uh hi. A kiphut khakna hang in',
    'Bang hun ciangin speed limit khengin tai hong kiphal hiam?',
    'Mawtaw saikel nih ii nungah na tai hi. Tua mawtaw saikelte dam takin tai uh hi. Bang cih ding na hiam?',
    'Thawhtanni(Pizing) Monday nitak nai 5:00 ahi hi. Na taina lamzingah hih lim/ciaptehna na mu hi. Hih a nuaiate lak bang hih ding hong kiphal hiam?',
    'Hih a nuaiate sung panin banghun ciangin bus taina lamzing (bus lane) ah tai hong kiphal hiam?', 
    'Koi mawtaw penin U-turn ngah lo hiam?',
    'Mawtaw horn bang hunah zang thei na hiam?',
    'Mawtaw na hawl ciangin na mit tawh bang ci ding?',
    'Mawtaw pualama limlangte hih a nuaiate bangin a kidawk/lat theih nadingin bawlin:',
    'Mawtaw tam mahmahna lak ah mawtaw na hawl hi. Datsi a nem/Na datsi zat a tawm theih nadingin bangci ding?',
    'Mawtaw hawl thakte hong siam semsem cih na theihna hangin',
    'Hih lim/ciaptehna ii deihna bang hiam?',
    'Mawtaw dangte mu dingin koi mawtaw penin head check kisam ahi hiam?',
    'Hih lim/ciaptehna ii veilamah bang mawtawte khawl kiphal hiam?',
    'Mawtaw hawl ii haksatna lianpi khat pen',
    'Mawtaw A na hawl hi. Siat theihna pan bangci kikep ding na hiam?',
    'Naupai khat na pua hi. Tutna gakna bangci koih sak ding na hiam?',
    'Mawtaw A leh mawtaw B mailam lampi awng (mawtaw om lo) mahmah hi. Koi pen in makhelh (Taipeel) kingah hiam?',
    'Mawtaw A na hawl hi. Lampi kituahna panin taklamah na kihei nuam hi. Koi lamzing (lane) panin kihei ding na hiam?',
  ];

  var choice = [
    ['Sekbing hawl bek', 'Khe-a paite bek', 'A nih un'],
    ['100 metres', '150 metres', '200 metres'],
    ['Mawtaw B bek', 'Mawtaw C bek', 'Mawtaw B ahi a, Mawtaw C ahi zong awn lo ding'],
    ['Mawtaw B in lam hong awn ding', 'Mawtaw B na awt kul ding', 'Mawtaw hawlten kua awn zaw ding cih deih tel thei'],
    ['Bang hun bang hunin giit nihte na kan/pel thei ding hi', 'Na mai-a mawtaw sim loh mawtaw dang a om kei leh makhelh dingin giit na kaan/pel thei ding hi',
	  'Na mai-a te makhelh dingin giit na pel/kaan peuhmah kei ding hi'],
    ['Mawtaw hawl siamna pen a pianken ngiat uh hi', 'Mawtaw tawh kisai thuaksa leh tuahsa (experiences) tampi na nei khin uh hi', 'Mun ngeina khat bekah mawtaw a hawl man uh hi'],
    ['I tuahsiat theih na dingte kancianna, sin cianna leh a kisam banga malak kholhna', 'Mawtaw kitaal theihna munte a kikep theihna', 'Na mawtaw hoih taka kep/puah theihna'],
    ['Mawtaw A hawlpa in mawtaw B lam a awt loh manin', 'Mawtaw B hawlpa in a lungsim pia lo ahih manin Mawtaw A mu lo', 'Mawtaw B hawlpa in lamka bawm lut dingin hat hawl lua mahmah hi'],
    ['Na ihmut hun ngei hong tun ciang' ,'Coffee na dawn khit teh', 'Damdawi nek ding na mangngilh teh'],
    ['Manglang takin handbrake zang ding', 'Brake sikna nawhsa tak leh nakpi taka sik(pump) ding', 'Brake khek lo dingin a horn pia den ding'],
    ['Saikel tuang pen in lam ong kan khak leh a khawl pah thei dingin dam tai (slow down) ding', 'Saikel tuang pen in lam ong awn ding ahih manin na tai ngeina bangin tai suak ding', 'Saikel tuang na awt theih nadingin nakpi takin brake sik ding'],
    ['Lampi ah a hi lo, mun awng khat peuhah mawtaw hawl kisin ding', 'Mawtaw sinsak nadinga licence neite tung pan lesson sawm beek kah ding', 'Mi siamte makaihna nuaiah nai 120 sung beek mun leh mual tuamtuamah mawtaw hawl kisin ding'],
    ['Kiphal ciang BAC te tawh a lauhuai dan kikim/kibang', 'Kiphal ciang BAC te sangin tawmin lauhuai zaw deuh', 'Kiphal ciang BAC te tawh tehin nakpi takin lauhuai zaw tham hi'],
    ['Mawtaw a hithei zaha dam tai sak dingin lampi pan veilamah ahih theih leh neh ding', 'Mawtaw mei tang sak dingin horn ging sak ding', 'Mawtaw B pen khial zaw ahih tak teh, na tai ngei banga tang taka tai suak ding'],
    ['40 metres', '89 metres', '140 metres'],
    ['Lam kawi', 'Lam naal', 'Lam phawk'],
    ['Nipi kal tampi guah a zuk kei leh', 'Guah zuk a kipat tuung teng', 'Guah nai bangzah hiam khat a zuk khit teh'],
    ['50 km/h', '60 km/h', '80 km/h'],
    ['Them khat hat sak deuh ding', 'Dam tai deuh ding', 'Hat ngei banga tai suak ding'],
    ['Mai lam 45km ciangah lam kawi om', 'Lam kawina munte ah a tawmpen 45 km/h a hat sak ding', 'Lam kawina munte ah a tampen 45 km/h sanga hat zaw sak lo ding'],
    ['Khawl ding', 'Khawl nadinga dam pai sak (slow down) ding', 'Horn pia kawmin tai suak ding'],
    ['Singlamteh banga lamka', 'T-laimal banga lamka', 'Lamka bawm/thuam '],
    ['Mai-ah T-lamka om', 'Veilam zingpi (Left lane) bei, zing dangah tai dingin kiging in', 'Veilam zingpi-ah na tai leh dam damin tai in'],
    ['A kang ki gitna tungah hawl ding', 'Tua akang kigit pen neh theihzah in neih ding', 'Tua a kang kigit ii vei lam ah hawl dingin, lampi ii veilam ah ahi thei zah in neh ding'],
    ['Mai lamah tang taka tai suak ding ahih keileh taklamah kihei/pial ding hong kiphal', 'Mai lamah tang taka tai suak thei ding, ahizongin taklamah kihei/pial thei lo ding', 'Taklamah pial/kihei thei, ahizong veilamah kihei/pial thei lo'],
    ['A tawntungin', 'Mawtaw hawl hun (driving condition) a hoih ciang', 'Mawtaw hawl hun (driving condition) a hoih loh ciang'],
    ['Mawtaw saikel in', 'Mawtaw A in', 'Lamka bom a tung nunung zaw pen in lam awn ding hi'],
    ['Warragul lam paikhiat(exit)na ding 2 km kisam lai', 'Warrangul pan 2 km kheng khin', 'Warragul pai nading paikhia (exit) pah in'],
    ['Mawtaw A bekin', 'Mawtaw B bekin', 'A nih un pia tuak ding'],
    ['A tawntung in', 'Bus pen in lamzingpi (lane) a khel/laih ciang bekin', 'Bus pen a khawlna lam gei veilam lamzingpi (left lane) pan hong pai khiat ding ciang bekin'],
    ['Mawtaw a kihei khit masiah ngak ding', 'Mawtaw a kihei masiah na horn mek ding', 'Mawtaw kiheina ii veilamah khetawh pai na lampiah kihen tantan in peel ding'],
    ['GPS a aw ging sak lo ding, a video lim (image) bek zang ding', 'Zinkhiat/paikhiat ma-in GPS setting khol ding', 'Mawtaw hawl kawma a bat det kullo dingin GPS a phei tungah koih ding'],
    ['Lampi ih theihna sate ah nai tampi sung mawtaw kisin ding leh lampi theih ngei nailonate ah a siamsate\' makaihna tawh mawtaw hawl sin ding', 'Kuama makaih lo-a mawtaw hawl tawh kisai i tuah ngei loh leh theih ngeih lohte ei le ei-a nawk/phu ding', 'License test ong nahih manin hong kimuang sak semsem'],
    ['Pumpi mahmah kihel kul', 'Nakpi taka kisinkholh kul', 'Kitaitehna(kidemna) nasia lua'],
    ['Nang hong tei sak (ihmut suak sak lo) ding hi', 'Hong tung thei ding lauhuai siatnate (hazards) hong thei sak thei', 'Mawtaw hawl siamna na ngah semsem ding hi'],
    ['Hong makhelh theihlohna dingin lampi laizang zik nai thei penah hawl ding', 'Hong makhelh lohna dingin mawtaw hazard mei taang tawh hilh ding', 'Speed kidawm kawmin na veilam lamzik (left lane) lamah tai ding'],
    ['A manlang thei pena brake sik ding', 'Tha khata mawtaw hong lehpaite lamah kinunghei vat ding', 'Brake sik in, dam-tai-sak (slow down) dinga, kiging ding'],
    ['Lam kabom na kan main, dam tai sak dingin na taklamah mawtaw ong pai hiam cih en ding', 'Lampi kituahna (lamka bom) manlang taka na kan theih nadingin hat sak (accelerate) ding', 'Khawl ding'],
    ['Mawtaw te\'n khe-lampaite (pedestrain) lampi awn ding', 'Khe-lampaite (pedestrians) in mawtawte lampi awn ding', 'Lampi pen mawtaw pai nading/tot ding leh khe-lampai nadingin/tot ding zing nihin kikhen hi.'],
    ['Mai ah khe tawh lamkanna tuak ding', 'Mai ah Meileng lamkanna tuak ding', 'Lampi kituahna (lamka bom) tuak ding'],
    ['Veilam pan makhelh bek ding', 'Taklam zing (right lane) peuhmah pan makhelh (overtake) lo ding', 'Mi na makhelh ding ciang ahi a, lampi a tawi luat ciang bekin taklam-zing (right lane) ah hawl hong kiphal bek hi'],
    ['Metre 1 bang peuhmah in kihal sak ding', 'Metre 2 bang peuhmah in kihal sak ding', 'Metre 3 bang peuhmah in kihal sak ding'],
    ['Bang bang ahi zongin mawtaw hawl hong kiphal nawn peuhmah lo hi', 'Dongtuak hun (emergency) te bekah hawl thei ding', 'Nasepna mun zuat nadingin transport dang zat ding a om het kei leh, mawtaw hawl thei bek ding'],
    ['10 km/h ciangah', '20 km/h ciangah', 'Lampi-a hat theih ding zah kiciangtan (speed limit) zah in'],
    ['Hat sak ding', 'Horn mek/pia ding', 'Na hat ngei banga tai ding'],
    ['Khe-lampai I bek', 'Khe-lampai II bek', 'A nih un'],
    ['Traffic light(mei) omna lampi kituahna(lamka bom) ah', 'Mawtaw tot lohna lam nawl (safety zone) ah', 'Mawtaw tot theih loh dinga lampi tung a kibo sak tuam munte (traffic island) ah'],
    ['Khawl ding', 'Kidawm takin hawl suak ding', 'A eng (green light) a taan dong ngak ding'],
    ['Lampi kituahna na tun ma-in khawl ding', 'Lampi kituahna na tun ma-in dam tai ding', 'Damdam in lampi kituahna(lamka bom)ah lut suak ding'],
    ['Cikmah hun in', 'Bang hun, bang hun in', 'Signal na piak a, makhelh ding a lauhuai loh ciang'],
    ['Lamzin (lane) khat peuhpeuh', 'X a san tawh a kiciamtehna lamzin (lane)', 'A eng teipi(green arrow) ahih kei leh a kang teipi( white arrow) tawh a kiciamteh lamzin (lane) khat peuhpeuh'],
    ['Zana mawtaw hawl lo ding, a hangin tatkhelhna theihna (a luahuai) tam hi', 'Mawtaw hawl a siam khinsa khatpeuh makaihna bek tawh zanin mawtaw hawl kisin ding', 'Tat khelh baih mahmah ahih manin dam takin hawl ding'],
    ['40 km/h ciangah ahih keh, 40 km/h sanga a tawmzaw in mawtaw hawl ding/tai ding', '40 km/h sanga hat zaw-a hawl/tai ding', 'Tua kipan 45 km ciangah khe-lampai om hiam cih limtak en ding'],
    ['Mawtaw na hawl ma-in na tha a zan dong ihmu masa ding', 'Coffee dawn khit teh mawtaw hawl khia thei pan ding', 'Mawtaw hawl ma-in windows hong in radio ngai ding'],
    ['1 second', '5 seconds', '10 seconds'],
    ['Nunglam etna maan thuah ding, tua hileh kimukim (blind spot omlo) ding', 'A kidawklo mun (blind spot) te thei-in a hunhunin head check hih zel ding', 'A hunhun in mit ki-en sak ding'],
    ['Experience (a taka tuahna) leh kisinna tampi a neih ciang bek un', 'Reflexes hoih neih mahmah ahih manun thukhensat man nei thei pah uh hi', 'Mawtaw hawl sinna hun nih a zawh khit uh teh'],
    ['50 metres', '100 metres', '200 metres'],
    ['Na kiheina ding 30 metres bang a gamla panin theisakna (signal) pia ding', 'Dam tai sakin, mawtaw B na khen khit teh theihsakna (signal) pia-in kihei ding', 'Khawl in la, mawtaw B awn phot in. Tua khit teh, theihsakna (signal) pia in la, kihei pan in.'],
    ['Khe tawh lamkante nataih khak lohna dingin, mawtaw hatna na khiap ding na tavuan hi', 'Khe tawh lamkan te-in lam a kan ma-in khua a hek ding a tavuan hi', 'Khe-a lamkan mipa/minu pen naupang ahih leh bek na khawl ding na tavuan hi.'],
    ['Tram pai sak phot in la, tua khit teh kihei pan in', 'Na kihei theih nadingin manlang takin tram makhelh vatin', 'Tram paina kantan hong kiphal lo ahih manin na mailamah tangtakin pai suakin'],
    ['Tram hawlpa kongkhak tawh kitangin khawlin', 'Tram nunglam/taw tawh kitangin khawlin', 'Tram nunglam kongkhak tawh kitangin khawlin'],
    ['U turn inla, kileh hei kik in', 'Emergency lane ah dam takin tai in', 'Pusuahna (Exit) masa penah pusuak in'],
    ['Limgelh (diagram) I', 'Limgelh (diagram) II', 'Limgelh (diagram) III'],
    ['Khe tawh lamkante ading in a lauhuai kei (safe) nak leh pai thei', 'Khe tawh lampaite in lam a kan khit uh teh pai thei', 'Minute 2 sung bang na ngak khit teh pai thei'],
    ['Na nunga mawtawte a kizekai sak khak loh nadingin manlangin lam kantan khia vat ding', 'Meileng lam na kantan ma-in na veilam leh na taklamah meileng hong pai leh pai loh limtak en masa ding', 'Alang lam a mawtawte\'n lam a kaan siang dong uh ngak in'],
    ['Na phul khak loh nadingin dam tak hawl ding, ahih kei leh khawl zaw liang ding', 'Kinawhtakin makhelh ziau ding', 'Sakolte\'n lam hong awt masiah horn mek ding'],
    ['Mawtaw A', 'Mawtaw B', 'Mawtaw C'],
    ['1 metre', '2 metres', '3 metres'],
    ['Khawl', 'Dam tai sak', 'Freeway a taite hatna tawh kituak dingin speed laih/khel ding'],
    ['Na nusiat ding lamzikah hong leh pai mawtaw a om loh ciang', 'Na nusiat ding lamzika meitaang lengmaw (orange) color a taang ciang', 'Na kihei nading lampi-a meitaang a eng (green) ciang'],
    ['Na taklam pan a round-about ah hong lut ding mawtaw te bek', 'Na veilama pan a round-about ah hong lut mawtaw te bek', 'Round-about sunga omsa mawtaw khempeuh'],
    ['Mawtaw B leh Mawtaw C', 'Mawtaw B kia/bek', 'Kuamah awt kul lo ( B ahi a, C ahizongin)'],
    ['Mawtaw maan hawngsa-a mawtaw hawl na', 'Zuu bangzah hiam khat dawnna', 'Coffee khauh mahmah dawnna'],
    ['A hang pen mawtaw hawl cimhuai mahmah tase leh kul mawk hi', 'Mai-ah bang tuak ding cih kiginkholh det kisam', 'Lamdang na sak theih nading hun leh munte ah mawtaw hawl ngei kei in'],
    ['Dinmun tuamtuamah na hawl theih lam na entel thei kik hi', 'Lampi ah mawtaw awt zia ding kihel hi', 'Na tot ding lampi (route) hoih pen na theithei hi'],
    ['Mawtaw hawl kawma radio hek/pei (adjusting)', 'Mawtaw tyre aa dinga a hoih bek zaha puak sak', 'Suang nen (gravel road)laka muanhuai tak a hawl'],
    ['Khe tawh a pai, tua khit teh mawtaw A, tua khit teh mawtaw B', 'Mawtaw A, tua khit teh mawtaw B, tua khit teh khe tawh a pai', 'Mawtaw A, tua khit teh khe tawh a pai, tua khit teh mawtaw B'],
    ['Mawtawpi(Truck) tai makhelh pah in', 'Mawtawpi hawlpa in a nungah na om lam a theih nadingin horn pia in', 'Mawtawpi nungah pai in la, a kihei theih nadingin mun awng sak in.'],
    ['A lauhuai lohna mun bekah mawtaw hawl ding', 'Mawtaw hawl tawh kisai tuah khak (experiences) tampi a neih uh ciang', 'Lampi tang saupi bekah mawtaw hawl kisin leh'],
    ['Mawtaw B lam awn ding', 'Mawtaw B makhelh theih nadingin hat sak ding', 'Mawtaw mit taang sak ding'],
    ['Mawtaw sungah music ngaih ding', 'A nunglam tutna-a tu a mi tawh kiho', 'Mobile phone tawh mi hopih'],
    ['Hand brake kai pah ding', 'Brake na zat ma-in mawtaw na control theih ding', 'Mawtaw hawlna panin na khut khah in, mawtaw dam pai sak in'],
    ['0.1', '0.2', '0.3'],
    ['Nai lang sung sawt 10 vei sin ding', 'Nai 2 leh a lang sung sawt 2 vei sin ding', 'Nai 5 sung sawt khat vei sin ding'],
    ['Tram a khawl khit teh', 'na U-turn teh', 'Lam hong khak nate na pelh ding teh'],
    ['A liam mipa/minu bangci cih en phot dingin tuakhit teh mawtaw hawl suak ding', 'Mi tawh kiphukha/tuahsia na hihna thu palik zum nai penah theisak ding', 'Van leh na a kisia a om ciang bekin palik zum nai penah na tuahsiat thu tun ding'],
    ['A kisin lai (learner permit) mawtaw hawlte', 'P1 Probationary License nei mawtaw hawlte', 'P2 Probationary License nei mawtaw hawlte'],
    ['Na dam tai theihna pen zah', 'Na hat tai theihna pen zah', 'Na tai hat zah ding a kideih zah'],
    ['Saturday zing nai 10:00 pan', 'Monday zing nai 8:30 pan', 'Friday zing nai 10:00 pan'],
    ['Dam tai sakin khawl ding', 'Lamzik zawm(next lane) ah kidawm takin kisuan ding', 'Tai suak dingin pusuahna(exit) masa penah pusuak(exit) ding'],
    ['Emergency lane ah khawl ding', 'Leihawm(tunnel) sung pan pusuak sawm phot ding', 'Mawtaw mailam mit/meivak sumit ding'],
    ['Position I', 'Position II', 'Position III'],
    ['Bus makhelh ding kiphal lo', 'Lampi a neu leh bus in lampi hong awn ding hi', 'Na taina lamzik(lane) ah bus lut sak dingin na kigin ding hi'],
    ['90 km/h vive tawh tai ding', '110 km/h vive tawh tai ding', 'A hun manman in 90 km/h leh 110 km/h kikalah khelin tai ding'],
    ['35 metres sanga tam zawkna pan dam pai ding kisam hi', '35 metres sanga tawm zawkna pan dam pai ding kisam hi', 'Khuahun in brake khawl sakna tawh kisai lo hi.'],
    ['X lam bekah', 'Y lam bekah', 'X lam ahih keh Y lamah'],
    ['Meileng mun khat lam bek panin hong tai ding hi', 'Meileng lampi nih tawnin meileng nih a kitonin tai khawm lo hi', 'Meileng khatin hong kheng khit teh koi lam zawzaw panin a dang khat hong tai kik thei hi'],
    ['Khawl ding', 'Dam taka tai meileng lam kan ding', 'Horn pia-in manlang takin meileng lam kan ding'],
    ['Mai-ah khawl(stop)ding ciaptehna/lim om', 'Mai-ah a lauhaui lam kituahna om', 'Mai-ah lamlak (Traffic) mei om'],
    ['Mawtaw peuhmah khawlin lam awn ding', 'Khe lampaite peuhmah khawl ding', 'Mawtaw dang hong tai a om ciang bekin mawtaw khawl ding'],
    ['Mawtaw B taklama a kihei ma-in', 'Mawtaw B taklama a kihei khit teh', 'Mawtaw A taklama kihei kiphal lo'],
    ['Korumburra gamlatna 440 km hi', 'Leongatha lam paina pen hih lampi hi', 'Lampi B440 na tot suak leh Poowong na tung ding hi'],
    ['60 km/h', '80 km/h', '100 km/h'],
    ['Khuasung (inn om na buit-up area) te ah hawl kei in', 'Mawtaw khawlna munte na naih ciangin damdam hawlin tuahileh siat theihna pan na kikem thei ding hi', 'Siatna hong tun theih ding peuhpeuh ah horn pia in'],
    ['Khawl ding', 'Khe tawh lampai a om leh om loh en kawmin damdam a hawl ding', 'Veilam zikah kihei-in 10 km/h-a tai in hawl ding'],
    ['Mawtaw hawl kawmin a adjust theih leh', 'Mawtaw-ah kip tak a kithuaha, tua GPS tungbek ah a lungsim a om kei nak leh', 'A aw suaksak loin a phei tungah a koih nak leh'],
    ['Mawtaw A', 'Mawtaw B', 'Mawtaw C'],
    ['Mawtaw B kia/bek', 'Mawtaw C kia/bek', 'Mawtaw B leh Mawtaw C'],
    ['Lampi M79 ah na tai hi', 'Kyneton na tun ma-in Harcourt na tung ding hi', 'Harcourt huamsungah 50 km/h hat bekin na tai/hawl ding hi'],
    ['A tawntungin na lu tangsak loin om in', 'Nunglam etna maante panin na nunglam na muh thei hiam cih telin', 'Na liangko tung lamah na lu hekin mawtaw nunglam etna maan pan ahizong in, a panga padenpoh (side windows)a nunglam etna maan pan ahi zong in check ding'],
    ['Minute 10 maw, minute 20 maw, minute 30 ahih ke\'h nai khat', 'Nai khat val hi leh', 'Minute 10 sang sawt zaw lo hi leh'],
    ['Padenpoh khat peuh hongin hawl in', 'Na teei theih nadingin nang leh nang na kilauh sak sawmin a hatzaw in hawlin', 'Khawl inla, ihmu phot in'],
    ['Dam takin taklamah kihei in', 'Mawtaw B in bangcih hiam cih ngak phot in', 'Mailamah dam takin hawl inla, lampi laizangah ngakin'],
    ['Mi makhelh ding ahih ke\'h lampi a toi luat leh', 'Tai hatzah ding a kici zah tawh na tai leh', 'Bang hun, bang hunah'],
    ['Mawtaw A kia/bek in', 'Mawtaw B kia/bek in', 'A nih un'],
    ['na dawn ngei zah mah dawn in BAC na tehnak leh na kithei ding hi', 'Na dawn ngeina zah mah na dawn hangin na BAC phazah na thei cian ngei kei ding hi', 'Bia (Beer) bungkhat (can) bek na dawn leh na BAC pen a kiphal zah sangin niam zaw hi na ci ngam bek ding hi'],
    ['Na nunga mawtawte hatna zah tawh kituaka na tai/hawl hang', 'A lem hun cianga makhelh sawm/nuam', 'Na mipuak (passengers) te\'n hong sawl manun'],
    ['Second 2 sung ciang peuhmah', 'A tawmpen Second 5 sung peuhmah', 'Second 10 sanga sawt zaw sung peuhmah'],
    ['Mawtaw B kia/bek', 'Mawtaw C kia/bek', 'A nih in'],
    ['Limsuaih I kia/bek', 'Limsuaih II kia/bek', 'A nih un'],
    ['Mipua mawtaw neute', 'Vanpua mawtaw neute', 'Mawtaw 4.5 tonnes sanga gik zaw peuhmah'],
    ['Hong lehpai mawtawte bek', 'Hong makhelh mawtawte bek', 'Mawtaw khempeuh leh khe tawh lampaite khempeuh'],
    ['Khawl dingin, mawtaw dangte pai sak phot ding', 'Hawl/tai ngeina zah (speed) hat mah tawh tai/hawl suak ding', 'Pusuakna(exit) lampi na tun khit phetin na mawtaw hatna khel(adjust) ding'],
    ['Path I', 'Path II', 'Path I ahih kei leh Path II'],
    ['Lim/ciaptehna ii taklamah a sawtpen nai khat sung', 'Lim/ciaptehna ii veilamah a sawtpen nai khat sung', 'Lim/ciaptehna ii taklamah a sawtpen minute khat sung'],
    ['A tawntungin', 'Khe tawh paina lampi (footpath) na muh cian theih loh ciangin', 'Cikmahciang'],
    ['A hatna zah mah tawh hawl/tai suak ding', 'Khawl ding', 'Dam pai sak in khe tawh lampaite ih taih khak lohna dingin kiging ding'],
    ['Banghun banghunin', 'Mawtaw B na makhelh ding teh', 'Mawtaw nihte geel 80 km/h sanga hatzaw-a a tai uh ciang'],
    ['Siattuak theihsakna (hazard) mei taang sak ding', 'Taklam kihei ding theihsakna mei taang sak ding', 'Mawtaw mai meitaang sak lela ding'],
    ['Mawtaw B mai ah', 'Mawtaw B leh Mawtaw C kikal', 'Mawtaw C leh Mawtaw D kikal'],
    ['Lampi kil, lam ngei a giit naipak kizawmsuak', 'Lampi laizanga giit nih paikhawm, a kaang kizawmsuak', 'Lampi laizanga giit, a kaang, a kizawmsuak lo ( a tawngtawng broken white line)'],
    ['Vanpua mawtawpite khawl ding kiphal hi', 'Hih kiimah hih hun in mawtaw na khawl sak leh hong kikaih khiat sak ding hi', 'Hih kiima vanpua mawtawpite\'n mawtaw dangte sangin thu nei zaw uh hi'],
    ['Bangtan hiam khat a taangin lehtai in', 'A koina ding munah a hat thei penin lever teen (accelerate) in', 'Hat sak semsem in la, thakhatin brake kang vat in'],
    ['Mawtaw A', 'Mawtaw B', 'Mawtaw C'],
    ['Mawtaw B pen mawtaw A zomah a om ciang bekin', 'Mawtaw B in a taina lamzingah mawtaw A hong lut theihna dingin nakpi taka brake a sik ciang bekin', 'A tawntungin'],
    ['Mawtaw B lam na awn ding hi', 'Mawtaw B in lam hong awn ding hi', 'Lampi kituahna a tung nunung zaw peuhpeuh in lam awn ding hi'],
    ['Mawtaw A', 'Mawtaw B', 'Lampi kituahna a tung nunung zaw mawtaw in'],
    ['Mawtaw B leh Mawtaw C', 'Mawtaw B kia/bek', 'Mawtaw C kia/bek'],
    ['Mawtaw A kia/bek', 'Mawtaw B kia/bek', 'Mawtaw A leh mawtaw B'],
    ['Lampi ii veilam tawh akineh thei penin', 'A tawng tawnga giit kaang a tawng( borken white line) ii veilam tawh akinai thei penin', 'Lamzing laizang tawh a kinai thei penin'],
    ['Setbing tuang pen kia/bek', 'Mawtaw B kia/bek', 'Setbing tuang leh mawtaw B te'],
    ['Mawtaw A', 'Mawtaw B', 'Mawtaw C'],
    ['Sun sung bekin na sin ding hi', 'Sun leh zan hun tuamtuamah na sin ding hi', 'Lampi a awn hun ciang bekin na sin ding hi'],
    ['Hong hilh pa/nu in na hih ding ong hilh ma-in nang na hih ding na thei khin hi', 'Mawtaw hawl dangte a khialh uh ciangin na hehsuak hi', 'Khawlna ciaptehna(stop sign) panin na taikhiat zal teh'],
    ['Dam takin hawl suakin', 'Na hat ngeina zahin hawl zom suak in', 'Hawl/Tai zawm dinga hun hoih masiah khawl in'],
    ['Bangmah theihsakna pia loin mawtaw A a khawl manin', 'Mawtaw C hat tai lua mahamah', 'Mawtaw B in en masa lopi-in veilamah a kikhin hang'],
    ['Freeway ah mi na makhelh teh', 'Emergeny hunah', 'Cikmah hunin'],
    ['Veilam lamzingah mawtaw saikelte a kikhin theih nadingun horn pia in', 'Damtakin mawtaw saikelte makhelh in', 'Mawtaw saikelte nungah ngakin'],
    ['Mawtaw khawl/nga(park) ding', 'Na tot lamzing (lane) laih ding', 'Na passenger tuak sak ding'],
    ['Metres 100 sanga a nai zawkna veilamah kihei na sawm ciangin', 'Lamzing danga mawtawte a khawl uh ciangin', 'Lam pi-ah na kilehhek kik ding ciang'],
    ['Mawtaw A', 'Mawtaw B', 'Mawtaw C'],
    ['Mawtaw hawl dangte na omna mun natheihsak ding ciang', 'Mawtaw hawl dangte a hat tai luat uh cih hilhna dingin', 'Mawtaw hawl dangte alauhuai dinmun ahih lam na theih sak nop ciang'],
    ['Na mai-a mawtaw en gige in', 'Na kiim na paam en kawikawi in', 'Nunglam etna limlang en gige in'],
    ['Na liim', 'Mawtaw sung', 'Mawtaw kil'],
    ['Mawtaw dang tawh kiton dingin manlangin hatsak in', 'Lever tiin leh lever khiapna hanga puak daldal pelh sawm in', 'Na mai-a mawtaw na naih ciangin a gear sutin/ a gear phel in'],
    ['Kihei ding cianga gamla pipi tai cihdan a, hih khialh tawm neih semsem uh hi', 'Freeways ah hong hawl nawh zaw deuh uh hi', 'Zanin mawtaw hawl nuam se uh hi'],
    ['Mawtaw sung pan na pusuah kei nakleh lamnawla mawtaw khawlnate ah na ut tantan na khawl thei hi', 'Lamnawla mawtaw khawlnate ah minute nih ciang na khawl thei hi', 'Lamnawla mawtaw khawlnate ah na khawl kei ding hi'],
    ['Mawtaw A a hawl pen bekin', 'Mawtaw B a hawl pen bekin', 'Mawtaw hawlte geel in'],
    ['Vanpua mawtaw peuhmah', 'Tua gei leh a kiima inn lamna-a nasem mawtaw peuhpeuh', 'Vanpua mawtawpi(truck) te bek/kia'],
    ['A gamlum mahmah passenger neih ciang', 'Mawtaw siang sitset leh hi sinsen a kep', 'Gamlapi-a mawtaw hawl gige'],
    ['Kihei siang ding', 'Saikel koilam pai cih na muh theih dong ngak ding', 'Lamlak mei (Traffic light) a san ahih dong ngak ding'],
    ['A gil puak tungah (Position A)', 'A gil puak nuaiah (Position B)', 'A khuk kimkotah (Position C)'],
    ['Mawtaw A aa ding bekin', 'Mawtaw B aa ding bekin', 'Kitai peel (makhelh) kingah lo'],
    ['Kihei dingin taklam lamzing(right lane) ah kisuanin', 'Kihei dingin veilam lamzing(lane) mahah om in', 'Mun khat beka tai theihna lampi (one-way road) ahih manin koi lam koi lam panin na kihei thei hi'],
  ];

  var correctAnswers = 
  [
    'A nih un', 
    '100 metres', 
    'Mawtaw B ahi a, Mawtaw C ahi zong awn lo ding',
    'Mawtaw B in lam hong awn ding',  
    'Na mai-a te makhelh dingin giit na pel/kaan peuhmah kei ding hi',
    'Mawtaw tawh kisai thuaksa leh tuahsa (experiences) tampi na nei khin uh hi',
    'I tuahsiat theih na dingte kancianna, sin cianna leh a kisam banga malak kholhna',
    'Mawtaw A hawlpa in mawtaw B lam a awt loh manin',
    'Na ihmut hun ngei hong tun ciang',
    'Brake sikna nawhsa tak leh nakpi taka sik(pump) ding',   
    'Saikel tuang pen in lam ong kan khak leh a khawl pah thei dingin dam tai (slow down) ding',
    'Mi siamte makaihna nuaiah nai 120 sung beek mun leh mual tuamtuamah mawtaw hawl kisin ding',
    'Kiphal ciang BAC te tawh tehin nakpi takin lauhuai zaw tham hi',
    'Mawtaw a hithei zaha dam tai sak dingin lampi pan veilamah ahih theih leh neh ding',
    '140 metres',
    'Lam naal',
    'Guah zuk a kipat tuung teng',
    '50 km/h',
    'Them khat hat sak deuh ding',
    'Lam kawina munte ah a tampen 45 km/h sanga hat zaw sak lo ding',
    'Khawl nadinga dam pai sak (slow down) ding',
    'Singlamteh banga lamka',
    'Veilam zingpi (Left lane) bei, zing dangah tai dingin kiging in',
    'Tua a kang kigit ii vei lam ah hawl dingin, lampi ii veilam ah ahi thei zah in neh ding',
    'Mai lamah tang taka tai suak ding ahih keileh taklamah kihei/pial ding hong kiphal',
    'Mawtaw hawl hun (driving condition) a hoih loh ciang',
    'Mawtaw A in',
    'Warragul lam paikhiat(exit)na ding 2 km kisam lai',
    'A nih un pia tuak ding',
    'Bus pen a khawlna lam gei veilam lamzingpi (left lane) pan hong pai khiat ding ciang bekin',
    'Mawtaw a kihei khit masiah ngak ding',
    'Zinkhiat/paikhiat ma-in GPS setting khol ding',
    'Lampi ih theihna sate ah nai tampi sung mawtaw kisin ding leh lampi theih ngei nailonate ah a siamsate\' makaihna tawh mawtaw hawl sin ding',
    'Nakpi taka kisinkholh kul',
    'Hong tung thei ding lauhuai siatnate (hazards) hong thei sak thei',
    'Speed kidawm kawmin na veilam lamzik (left lane) lamah tai ding',
    'Brake sik in, dam-tai-sak (slow down) dinga, kiging ding',
    'Khawl ding',
    'Mawtaw te\'n khe-lampaite (pedestrain) lampi awn ding',
    'Mai ah Meileng lamkanna tuak ding',
    'Mi na makhelh ding ciang ahi a, lampi a tawi luat ciang bekin taklam-zing (right lane) ah hawl hong kiphal bek hi',
    'Metre 1 bang peuhmah in kihal sak ding',
    'Bang bang ahi zongin mawtaw hawl hong kiphal nawn peuhmah lo hi',
    '10 km/h ciangah',
    'Na hat ngei banga tai ding',
    'A nih un',
    'Traffic light(mei) omna lampi kituahna(lamka bom) ah',
    'Kidawm takin hawl suak ding',
    'Lampi kituahna na tun ma-in khawl ding',
    'Signal na piak a, makhelh ding a lauhuai loh ciang',
    'A eng teipi(green arrow) ahih kei leh a kang teipi( white arrow) tawh a kiciamteh lamzin (lane) khat peuhpeuh',
    'Mawtaw hawl a siam khinsa khatpeuh makaihna bek tawh zanin mawtaw hawl kisin ding',
    '40 km/h ciangah ahih keh, 40 km/h sanga a tawmzaw in mawtaw hawl ding/tai ding',
    'Mawtaw na hawl ma-in na tha a zan dong ihmu masa ding',
    '5 seconds',
    'A kidawklo mun (blind spot) te thei-in a hunhunin head check hih zel ding',
    'Experience (a taka tuahna) leh kisinna tampi a neih ciang bek un',
    '200 metres',
    'Dam tai sakin, mawtaw B na khen khit teh theihsakna (signal) pia-in kihei ding',
    'Khe tawh lamkante nataih khak lohna dingin, mawtaw hatna na khiap ding na tavuan hi',
    'Tram pai sak phot in la, tua khit teh kihei pan in',
    'Tram nunglam/taw tawh kitangin khawlin',
    'Pusuahna (Exit) masa penah pusuak in',
    'Limgelh (diagram) III',
    'Khe tawh lampaite in lam a kan khit uh teh pai thei',
    'Meileng lam na kantan ma-in na veilam leh na taklamah meileng hong pai leh pai loh limtak en masa ding',
    'Na phul khak loh nadingin dam tak hawl ding, ahih kei leh khawl zaw liang ding',
    'Mawtaw B',
    '1 metre',
    'Freeway a taite hatna tawh kituak dingin speed laih/khel ding',
    'Na kihei nading lampi-a meitaang a eng (green) ciang',
    'Round-about sunga omsa mawtaw khempeuh',
    'Kuamah awt kul lo ( B ahi a, C ahizongin)',
    'Zuu bangzah hiam khat dawnna',
    'Mai-ah bang tuak ding cih kiginkholh det kisam',
    'Dinmun tuamtuamah na hawl theih lam na entel thei kik hi',
    'Suang nen (gravel road)laka muanhuai tak a hawl',
    'Mawtaw A, tua khit teh khe tawh a pai, tua khit teh mawtaw B',
    'Mawtawpi nungah pai in la, a kihei theih nadingin mun awng sak in.',
    'Mawtaw hawl tawh kisai tuah khak (experiences) tampi a neih uh ciang',
    'Mawtaw B lam awn ding',
    'Mobile phone tawh mi hopih',
    'Brake na zat ma-in mawtaw na control theih ding',
    '0.3',
    'Nai lang sung sawt 10 vei sin ding',
    'Lam hong khak nate na pelh ding teh',
    'Mi tawh kiphukha/tuahsia na hihna thu palik zum nai penah theisak ding',
    'P1 Probationary License nei mawtaw hawlte',
    'Na hat tai theihna pen zah',
    'Saturday zing nai 10:00 pan',
    'Lamzik zawm(next lane) ah kidawm takin kisuan ding',
    'Leihawm(tunnel) sung pan pusuak sawm phot ding',
    'Position II',
    'Na taina lamzik(lane) ah bus lut sak dingin na kigin ding hi',
    '90 km/h vive tawh tai ding',
    '35 metres sanga tam zawkna pan dam pai ding kisam hi',
    'X lam ahih keh Y lamah',
    'Meileng khatin hong kheng khit teh koi lam zawzaw panin a dang khat hong tai kik thei hi',
    'Khawl ding',
    'Mai-ah khawl(stop)ding ciaptehna/lim om',
    'Mawtaw peuhmah khawlin lam awn ding',
    'Mawtaw B taklama a kihei khit teh',
    'Leongatha lam paina pen hih lampi hi',
    '100 km/h',
    'Mawtaw khawlna munte na naih ciangin damdam hawlin tuahileh siat theihna pan na kikem thei ding hi',
    'Khawl ding',
    'Mawtaw-ah kip tak a kithuaha, tua GPS tungbek ah a lungsim a om kei nak leh',
    'Mawtaw C',
    'Mawtaw B leh Mawtaw C',
    'Lampi M79 ah na tai hi',
    'Na liangko tung lamah na lu hekin mawtaw nunglam etna maan pan ahizong in, a panga padenpoh (side windows)a nunglam etna maan pan ahi zong in check ding',
    'Minute 10 maw, minute 20 maw, minute 30 ahih ke\'h nai khat',
    'Khawl inla, ihmu phot in',
    'Mawtaw B in bangcih hiam cih ngak phot in',
    'Mi makhelh ding ahih ke\'h lampi a toi luat leh',
    'A nih un',
    'Na dawn ngeina zah mah na dawn hangin na BAC phazah na thei cian ngei kei ding hi',
    'A lem hun cianga makhelh sawm/nuam',
    'A tawmpen Second 5 sung peuhmah',
    'A nih in',
    'Limsuaih II kia/bek',
    'Mawtaw 4.5 tonnes sanga gik zaw peuhmah',
    'Mawtaw khempeuh leh khe tawh lampaite khempeuh',
    'Pusuakna(exit) lampi na tun khit phetin na mawtaw hatna khel(adjust) ding',
    'Path I',
    'Lim/ciaptehna ii taklamah a sawtpen nai khat sung',
    'Khe tawh paina lampi (footpath) na muh cian theih loh ciangin',
    'Dam pai sak in khe tawh lampaite ih taih khak lohna dingin kiging ding',
    'Mawtaw B na makhelh ding teh',
    'Siattuak theihsakna (hazard) mei taang sak ding',
    'Mawtaw B leh Mawtaw C kikal',
    'Lampi laizanga giit, a kaang, a kizawmsuak lo ( a tawngtawng broken white line)',
    'Hih kiimah hih hun in mawtaw na khawl sak leh hong kikaih khiat sak ding hi',
    'Bangtan hiam khat a taangin lehtai in',
    'Mawtaw B',
    'A tawntungin',
    'Mawtaw B lam na awn ding hi',
    'Mawtaw B',
    'Mawtaw C kia/bek',
    'Mawtaw B kia/bek',
    'Lampi ii veilam tawh akineh thei penin',
    'Setbing tuang leh mawtaw B te',
    'Mawtaw A',
    'Sun leh zan hun tuamtuamah na sin ding hi',
    'Hong hilh pa/nu in na hih ding ong hilh ma-in nang na hih ding na thei khin hi',
    'Dam takin hawl suakin',
    'Mawtaw B in en masa lopi-in veilamah a kikhin hang',
    'Cikmah hunin',
    'Mawtaw saikelte nungah ngakin',
    'Na tot lamzing (lane) laih ding',
    'Metres 100 sanga a nai zawkna veilamah kihei na sawm ciangin',
    'Mawtaw B',
    'Mawtaw hawl dangte na omna mun natheihsak ding ciang',
    'Na kiim na paam en kawikawi in',
    'Mawtaw kil',
    'Lever tiin leh lever khiapna hanga puak daldal pelh sawm in',
    'Kihei ding cianga gamla pipi tai cihdan a, hih khialh tawm neih semsem uh hi',
    'Lamnawla mawtaw khawlnate ah na khawl kei ding hi',
    'Mawtaw A a hawl pen bekin',
    'Tua gei leh a kiima inn lamna-a nasem mawtaw peuhpeuh',
    'A gamlum mahmah passenger neih ciang',
    'Saikel koilam pai cih na muh theih dong ngak ding',
    'A gil puak nuaiah (Position B)',
    'Mawtaw A aa ding bekin',
    'Kihei dingin taklam lamzing(right lane) ah kisuanin',
  ];

}